## Golden-trace equivalence + determinism harness (docs/decisions/movement-substrate.md
## §4, §6.2). This mechanizes the projection-from-one-definition invariant:
##
##   given (kit, input_log), produce the full per-tick MovementState trajectory and
##   assert   interpreter == compiled   AND   interpreter == interpreter-repeat.
##
## The interpreter is the REFERENCE semantics; the compiled path (CompiledBaseMovement,
## generated by MovementCompiler from the same kit) must produce a bit-identical
## trajectory. Any divergence is a compiler bug (or a determinism bug) and FAILS
## loudly with the first diverging tick, field, and values reported.
##
## METHOD. Each driver runs ALONE in its own world, SEQUENTIALLY, recording the
## full per-tick trajectory; then the three recordings are compared. Sequential
## isolation matters: co-existing bodies share one physics space and would collide
## / desync, which is an artifact of the harness, not of the lowering. Per run a
## scripted input_log drives the REAL global Input each tick (action_press /
## action_release + a per-tick yaw), one physics frame advances the lone body, and
## the trajectory is snapshotted. Three runs: (A) interpreter, (B) compiled,
## (C) interpreter-repeat. Identical input + identical lone world → identical
## trajectory, so any difference is a lowering/determinism fault.
##
## The recorded trajectory excludes camera/FOV/roll (render-only, §3 step 5): it is
## velocity, global_position, collider height, the named timers, and active state.
##
## Run (windowed under xvfb per the spec):
##   nix develop --command bash -lc \
##     'xvfb-run -a godot4 --path . res://tests/golden_trace_test.tscn --quit-after 4000'
## Exits 0 iff every input_log matches across all three; else 1.
extends Node

const KIT_PATH := "res://movement/base.kit.json"

# Floating-point trajectory comparison tolerance. Same runtime, same arithmetic
# order → these should match to the bit; a tiny epsilon guards only against
# Vector3 component formatting, never masks a real divergence (we also report the
# max observed delta so a "passing but drifting" case is visible).
const EPS := 1e-6

var _pass_count := 0
var _fail_count := 0


func _ready() -> void:
	await _run()


func _run() -> void:
	print("\n=== aeriea movement SLICE 3 golden-trace test ===\n")

	for case in _input_logs():
		await _run_case(case["name"], case["log"], case["spawn"], case["with_walls"])

	print("\n=== RESULTS: %d passed, %d failed ===\n" % [_pass_count, _fail_count])
	get_tree().quit(0 if _fail_count == 0 else 1)


# ---------------------------------------------------------------------------
# Input logs — a per-tick list of {actions:[...], yaw:float}. Each entry is one
# physics tick. These exercise the key verbs across the kit.
# ---------------------------------------------------------------------------

func _input_logs() -> Array:
	return [
		{"name": "ground accel + friction", "spawn": Vector3(0, 1.2, 0), "with_walls": false,
			"log": _hold(["move_forward"], 40) + _hold([], 40)},
		{"name": "jump + coyote + buffer", "spawn": Vector3(0, 1.2, 0), "with_walls": false,
			"log": _hold([], 10) + _hold(["jump"], 3) + _hold([], 20)
				+ _hold(["move_forward"], 20) + _hold(["jump"], 2) + _hold([], 30)},
		{"name": "sprint slide entry + carve + cap + exit", "spawn": Vector3(0, 1.2, 0), "with_walls": false,
			"log": _hold(["move_forward", "sprint"], 35)
				+ _hold(["move_forward", "sprint", "crouch"], 6)
				+ _hold(["move_forward", "crouch", "move_left"], 25)
				+ _hold([], 30)},
		{"name": "wall-run incl. backward input", "spawn": Vector3(2.6, 2.0, 4.0), "with_walls": true,
			"log": _hold_v(["move_forward"], 25, 0.0)
				+ _hold_v(["move_backward"], 15, 0.0)
				+ _hold_v([], 25, 0.0)},
		{"name": "respawn below kill_y then recover", "spawn": Vector3(0, 1.2, 0), "with_walls": false,
			"log": _hold([], 5) + _hold(["move_forward"], 25)},
		{"name": "bullet jump from slide (SLICE 4 pure-data verb, triggered by jump from slide)", "spawn": Vector3(0, 1.2, 0), "with_walls": false,
			"log": _hold(["move_forward", "sprint"], 35)
				+ _hold(["move_forward", "sprint", "crouch"], 4)
				+ _hold(["move_forward", "crouch", "jump"], 3)
				+ _hold(["move_forward"], 30)},
		{"name": "bullet jump from slide while PITCHED UP (exercises the aim/look space directionality)", "spawn": Vector3(0, 1.2, 0), "with_walls": false,
			"log": _hold_vp(["move_forward", "sprint"], 35, 0.0, 0.6)
				+ _hold_vp(["move_forward", "sprint", "crouch"], 4, 0.0, 0.6)
				+ _hold_vp(["move_forward", "crouch", "jump"], 3, 0.0, 0.6)
				+ _hold_vp(["move_forward"], 30, 0.0, 0.6)},
		{"name": "wall-cling: airborne beside a wall holding cling latches, suppresses gravity, then releases (pure-data verb)", "spawn": Vector3(2.6, 3.5, 4.0), "with_walls": true,
			"log": _hold([], 6)
				+ _hold(["cling"], 40)
				+ _hold([], 25)},
		{"name": "aim-glide: jump then hold aim on descent slows the fall (pure-data verb)", "spawn": Vector3(0, 1.2, 0), "with_walls": false,
			"log": _hold([], 6)
				+ _hold(["jump"], 2)
				+ _hold([], 14)
				+ _hold(["aim"], 60)},
	]


## n ticks holding `actions` (yaw 0).
func _hold(actions: Array, n: int) -> Array:
	return _hold_v(actions, n, 0.0)

func _hold_v(actions: Array, n: int, yaw: float) -> Array:
	return _hold_vp(actions, n, yaw, 0.0)

## n ticks holding `actions` at a given yaw AND pitch (radians, +up). Pitch drives
## the `aim`/look space so directional verbs (bullet jump) launch along the full
## look vector — this is how the golden trace exercises pitch-tracking.
func _hold_vp(actions: Array, n: int, yaw: float, pitch: float) -> Array:
	var out: Array = []
	for _i in n:
		out.append({"actions": actions.duplicate(), "yaw": yaw, "pitch": pitch})
	return out


# ---------------------------------------------------------------------------
# Worlds
# ---------------------------------------------------------------------------

## Build one self-contained world (floor; optional wall-run corridor) with an
## InterpretedPlayer host. `compiled` selects the driver. Returns {level, player}.
func _build_world(spawn: Vector3, with_walls: bool, compiled: bool) -> Dictionary:
	var level := Node3D.new()

	var floor_body := StaticBody3D.new()
	var floor_shape := CollisionShape3D.new()
	var box := BoxShape3D.new()
	box.size = Vector3(80, 1, 80)
	floor_shape.shape = box
	floor_body.add_child(floor_shape)
	floor_body.position = Vector3(0, -0.5, 0)
	level.add_child(floor_body)

	if with_walls:
		# Right wall (WallB) mirroring scenes/test_level.tscn: surface near x=3.0.
		var wall := StaticBody3D.new()
		var ws := CollisionShape3D.new()
		var wbox := BoxShape3D.new()
		wbox.size = Vector3(1, 5, 18)
		ws.shape = wbox
		wall.add_child(ws)
		wall.position = Vector3(3.5, 2.5, 8)
		level.add_child(wall)

	var spawn_marker := Marker3D.new()
	spawn_marker.name = "SpawnPoint"
	spawn_marker.position = spawn
	level.add_child(spawn_marker)

	var player := InterpretedPlayer.new()
	player.name = "Player"
	player.use_compiled = compiled
	player.position = spawn
	player.spawn_path = NodePath("../SpawnPoint")
	level.add_child(player)

	add_child(level)
	return {"level": level, "player": player}


# ---------------------------------------------------------------------------
# Trajectory capture + comparison
# ---------------------------------------------------------------------------

## Snapshot the trajectory-relevant MovementState of a host this tick.
func _snapshot(player: InterpretedPlayer) -> Dictionary:
	var timers := {}
	for k in player.interpreter.timers:
		timers[k] = float(player.interpreter.timers[k])
	return {
		"state": player.interpreter.active_state,
		"vel": player.velocity,
		"pos": player.global_position,
		"col_h": player._capsule.height,
		"timers": timers,
		"wall_normal": player.interpreter.wall_normal,
		"wall_side": player.interpreter.wall_side,
	}


## Compare two per-tick snapshots. Returns "" if equal, else a description of the
## first diverging field with both values.
func _diff(a: Dictionary, b: Dictionary) -> String:
	if a["state"] != b["state"]:
		return "state %s vs %s" % [a["state"], b["state"]]
	if not _vec_eq(a["vel"], b["vel"]):
		return "vel %s vs %s" % [a["vel"], b["vel"]]
	if not _vec_eq(a["pos"], b["pos"]):
		return "pos %s vs %s" % [a["pos"], b["pos"]]
	if absf(a["col_h"] - b["col_h"]) > EPS:
		return "col_h %f vs %f" % [a["col_h"], b["col_h"]]
	if absf(a["wall_side"] - b["wall_side"]) > EPS:
		return "wall_side %f vs %f" % [a["wall_side"], b["wall_side"]]
	if not _vec_eq(a["wall_normal"], b["wall_normal"]):
		return "wall_normal %s vs %s" % [a["wall_normal"], b["wall_normal"]]
	var keys := {}
	for k in a["timers"]:
		keys[k] = true
	for k in b["timers"]:
		keys[k] = true
	for k in keys:
		var av: float = a["timers"].get(k, 0.0)
		var bv: float = b["timers"].get(k, 0.0)
		if absf(av - bv) > EPS:
			return "timer[%s] %f vs %f" % [k, av, bv]
	return ""


func _vec_eq(a: Vector3, b: Vector3) -> bool:
	return (a - b).length() <= EPS


func _max_delta(a: Dictionary, b: Dictionary) -> float:
	var d := 0.0
	d = maxf(d, (a["vel"] - b["vel"]).length())
	d = maxf(d, (a["pos"] - b["pos"]).length())
	d = maxf(d, absf(a["col_h"] - b["col_h"]))
	return d


# ---------------------------------------------------------------------------
# Drive one case across three worlds in lockstep.
# ---------------------------------------------------------------------------

func _all_actions() -> Array:
	return ["move_forward", "move_backward", "move_left", "move_right", "sprint", "crouch", "jump", "cling", "aim"]


func _apply_input(entry: Dictionary, p: InterpretedPlayer) -> void:
	var want: Array = entry["actions"]
	for action in _all_actions():
		if not InputMap.has_action(action):
			continue
		if want.has(action):
			Input.action_press(action)
		else:
			Input.action_release(action)
	Input.flush_buffered_events()
	p._yaw = entry["yaw"]
	p._pitch = float(entry.get("pitch", 0.0))


## Drive one lone world through the input_log and return its per-tick trajectory
## (Array[Dictionary] snapshots). The world is freed before returning.
func _record_run(log: Array, spawn: Vector3, with_walls: bool, compiled: bool) -> Array:
	var w := _build_world(spawn, with_walls, compiled)
	var p: InterpretedPlayer = w["player"]

	# Settle frames with no input, identical for every run.
	for action in _all_actions():
		if InputMap.has_action(action):
			Input.action_release(action)
	Input.flush_buffered_events()
	await get_tree().physics_frame
	await get_tree().physics_frame

	var traj: Array = []
	for entry in log:
		_apply_input(entry, p)
		await get_tree().physics_frame
		traj.append(_snapshot(p))

	for action in _all_actions():
		if InputMap.has_action(action):
			Input.action_release(action)
	Input.flush_buffered_events()
	w["level"].queue_free()
	await get_tree().process_frame
	return traj


## Compare two recorded trajectories tick-by-tick. Returns {div, tick, max_delta}.
func _compare(a: Array, b: Array) -> Dictionary:
	var first_div := ""
	var div_tick := -1
	var max_delta := 0.0
	var n: int = mini(a.size(), b.size())
	for t in n:
		max_delta = maxf(max_delta, _max_delta(a[t], b[t]))
		if first_div == "":
			var d := _diff(a[t], b[t])
			if d != "":
				first_div = d
				div_tick = t
	if first_div == "" and a.size() != b.size():
		first_div = "trajectory length %d vs %d" % [a.size(), b.size()]
	return {"div": first_div, "tick": div_tick, "max_delta": max_delta}


func _run_case(case_name: String, log: Array, spawn: Vector3, with_walls: bool) -> void:
	GameSettings.reset_all()
	# Sequential, isolated runs (one lone body per run — no cross-body collisions).
	var traj_interp: Array = await _record_run(log, spawn, with_walls, false)
	var traj_compiled: Array = await _record_run(log, spawn, with_walls, true)
	var traj_repeat: Array = await _record_run(log, spawn, with_walls, false)

	var ec := _compare(traj_interp, traj_compiled)
	var rep := _compare(traj_interp, traj_repeat)

	_assert(
		"[%s] interpreter == compiled over %d ticks" % [case_name, log.size()],
		ec["div"] == "",
		"max_delta=%s%s" % [_fmt_delta(ec["max_delta"]),
			"" if ec["div"] == "" else (", FIRST DIVERGENCE @tick %d: %s" % [ec["tick"], ec["div"]])]
	)
	_assert(
		"[%s] interpreter == interpreter-repeat (determinism) over %d ticks" % [case_name, log.size()],
		rep["div"] == "",
		"identical" if rep["div"] == "" else ("FIRST DIVERGENCE @tick %d: %s" % [rep["tick"], rep["div"]])
	)


func _fmt_delta(d: float) -> String:
	return String.num(d, 9)


func _assert(test_name: String, condition: bool, evidence: String) -> void:
	if condition:
		_pass_count += 1
		print("  PASS  %s  [%s]" % [test_name, evidence])
	else:
		_fail_count += 1
		print("  FAIL  %s  [%s]" % [test_name, evidence])
