## Golden-trace equivalence + determinism harness for the INTERACTION substrate
## (docs/decisions/affordance-substrate.md §7b, §8.2). Mirrors the movement kit's
## tests/golden_trace_test.gd. This mechanizes projection-from-one-definition:
##
##   given (kit, interaction_log), produce the full per-tick interactable-STATE
##   trajectory and assert  interpreter == compiled  AND  interpreter == repeat.
##
## The interpreter is the REFERENCE semantics; the compiled path
## (CompiledSandboxInteraction, generated by InteractionCompiler from the same kit)
## must produce a bit-identical trajectory. Any divergence is a compiler bug (or a
## determinism bug) and FAILS loudly with the first diverging tick/field/values.
##
## METHOD. Both drivers are PURE steppers over the SAME explicit state record; they
## need no scene/physics. A scripted interaction_log supplies, per tick, the resolved
## frame the host would build: focus id, held id (+ its tags), input edges
## (interact/throw), region members, and player-in-region. A tiny ScriptedHost
## replays the log and records grab/release/socket/impulse intents (so carry state
## evolves deterministically). Each driver runs ALONE over the same log; the three
## trajectories (A interpreter, B compiled, C interpreter-repeat) are compared.
##
## The recorded trajectory is the full sim state: every interactable's state record
## (flowing/fill/active/socketed/armed/triggered) plus the host's held id. Prompts
## are render-side (§3 step 5) and excluded from the hash.
##
## The logs exercise the sandbox's key chains: valve->spout->jug fill, grab/drop/
## throw, place arms beacon (the AND-gated trigger via reach), and unarmed-reach
## inert (the converse guard).
##
## Run (windowed under xvfb per the spec):
##   nix develop --command bash -lc \
##     'xvfb-run -a godot4 --path . res://tests/interaction_golden_trace_test.tscn --quit-after 4000'
## Exits 0 iff every log matches across all three; else 1.
extends Node

const KIT_PATH := "res://interaction/sandbox.kit.json"
const InterpScript := preload("res://scripts/interaction/interaction_interpreter.gd")
const CompiledScript := preload("res://scripts/interaction/generated/compiled_sandbox_interaction.gd")

const EPS := 1e-6
const DT := 1.0 / 60.0

var _pass := 0
var _fail := 0


func _ready() -> void:
	_run()


func _run() -> void:
	print("\n=== aeriea interaction golden-trace test ===\n")
	for case in _logs():
		_run_case(case)
	print("\n=== RESULTS: %d passed, %d failed ===\n" % [_pass, _fail])
	get_tree().quit(0 if _fail == 0 else 1)


# ---------------------------------------------------------------------------
# A scripted host: replays a per-tick frame spec and tracks carry intents so the
# held id evolves deterministically across grab/release/socket. This is the SAME
# host protocol the interpreter and the compiled path consume (host_build_frame /
# host_grab / host_release / host_apply_impulse / host_socket), with the physics
# realized as trivial bookkeeping (no scene needed for the affordance trajectory).
# ---------------------------------------------------------------------------

class ScriptedHost:
	extends RefCounted
	var _frame: InterpScript.ResolvedFrame = null
	var held_id: String = ""

	## Build this tick's frame from a spec dict and the current held id. The spec
	## supplies focus/edges/region members/player reach; held id comes from carry
	## state (grab/release mutate it), exactly as the live host's _held_id does.
	func build(spec: Dictionary, tags_of: Callable) -> void:
		var f := InterpScript.ResolvedFrame.new()
		f.focus_id = str(spec.get("focus", ""))
		f.edges = spec.get("edges", {})
		f.held_id = held_id
		if held_id != "":
			f.held_tags = tags_of.call(held_id)
		f.region_members = spec.get("region_members", {})
		f.player_in_region = spec.get("player_in_region", {})
		_frame = f

	func host_build_frame() -> InterpScript.ResolvedFrame:
		return _frame

	func host_grab(kit_id: String) -> bool:
		held_id = kit_id
		return true

	func host_release(_mode: String, _impulse: float) -> void:
		held_id = ""

	func host_apply_impulse(_magnitude: float) -> void:
		pass

	func host_socket(_owner_id: String, _body_id: String) -> void:
		# The socket field is recorded by the effect; carry clears.
		held_id = ""


# ---------------------------------------------------------------------------
# Interaction logs — a per-tick list of frame specs. Each entry is one tick.
# Region members / player reach are supplied directly (the host would sample them
# from Area3D overlaps; here we script them to exercise the chains deterministically).
# ---------------------------------------------------------------------------

func _logs() -> Array:
	# `expect`: final-tick {id: {field: value}} the interpreter MUST reach. This
	# guards against vacuous equivalence (both paths doing nothing would also match);
	# it proves the chains actually fire. `held` checks the final carry id.
	return [
		{
			"name": "valve toggle -> spout fills jug in stream",
			"log": _valve_fill_log(),
			"expect": {"valve": {"flowing": true}, "jug": {"fill": 1.0}},
		},
		{
			"name": "grab jug / drop / throw carry verbs",
			"log": _carry_log(),
			"expect_held": "",
		},
		{
			"name": "chain A: open valve, fill jug, place FULL jug -> pedestal active, beacon ARMS",
			"log": _chain_a_log(),
			"expect": {"pedestal": {"active": true, "socketed": "jug"}, "beacon": {"armed": true}},
		},
		{
			"name": "AND-gate: armed beacon + player reach -> triggers",
			"log": _armed_reach_log(),
			"expect": {"beacon": {"armed": true, "triggered": true}},
		},
		{
			"name": "converse guard: UNARMED reach is inert (no trigger)",
			"log": _unarmed_reach_log(),
			"expect": {"beacon": {"armed": false, "triggered": false}},
		},
		{
			"name": "place jug that is NOT full -> consumed but pedestal stays inactive, beacon never arms",
			"log": _place_empty_log(),
			"expect": {"pedestal": {"active": false, "socketed": "jug"}, "beacon": {"armed": false, "triggered": false}},
		},
		{
			"name": "SLICE 3 gate: lever ALONE is inert (open never set)",
			"log": _gate_lever_only_log(),
			"expect": {"lever": {"thrown": true}, "plate": {"pressed": false}, "gate": {"open": false}},
		},
		{
			"name": "SLICE 3 gate: weight on plate ALONE is inert (open never set)",
			"log": _gate_plate_only_log(),
			"expect": {"lever": {"thrown": false}, "plate": {"pressed": true}, "gate": {"open": false}},
		},
		{
			"name": "SLICE 3 gate: lever AND plate -> gate OPENS (the second AND-gate convergence)",
			"log": _gate_both_log(),
			"expect": {"lever": {"thrown": true}, "plate": {"pressed": true}, "gate": {"open": true}},
		},
		{
			"name": "SLICE 3 gate: live close — both open it, then removing the weight closes it again",
			"log": _gate_open_then_close_log(),
			"expect": {"lever": {"thrown": true}, "plate": {"pressed": false}, "gate": {"open": false}},
		},
	]


## SLICE 3 — gate logs. The plate's `pressed` is driven by a box overlapping its
## `plate:pad` region (the same physics-seam in_region guard the spout uses); the
## lever is a command toggle. The gate's open is the AND of both, recomputed each tick.

## Throw the lever; never put a weight on the plate. The gate must stay closed.
func _gate_lever_only_log() -> Array:
	var log: Array = []
	log.append({"focus": "lever", "edges": {"interact": true}})   # throw lever
	for _i in 8:
		log.append({"focus": ""})                                  # no weight on plate
	return log


## Put a weight (a box) on the plate; never throw the lever. The gate must stay closed.
func _gate_plate_only_log() -> Array:
	var log: Array = []
	for _i in 8:
		log.append({"focus": "", "region_members": {"plate:pad": ["box"]}})
	return log


## Both chains: throw the lever AND stand a weight on the plate -> the gate opens.
func _gate_both_log() -> Array:
	var log: Array = []
	log.append({"focus": "lever", "edges": {"interact": true}})    # throw lever
	for _i in 8:
		log.append({"focus": "", "region_members": {"plate:pad": ["box"]}})
	return log


## Open it (both), then remove the weight -> plate springs back, gate closes (live).
func _gate_open_then_close_log() -> Array:
	var log: Array = []
	log.append({"focus": "lever", "edges": {"interact": true}})    # throw lever
	for _i in 6:
		log.append({"focus": "", "region_members": {"plate:pad": ["box"]}})  # opens
	for _i in 6:
		log.append({"focus": ""})                                  # weight gone -> closes
	return log


## Open the valve, then hold a jug in the stream for many ticks while flowing.
func _valve_fill_log() -> Array:
	var log: Array = []
	# Tick 1: focus valve, interact edge -> toggle flowing on.
	log.append({"focus": "valve", "edges": {"interact": true}})
	# Then hold the jug in the spout stream while flowing (no edges). The spout's
	# stream region contains the jug; the spout's tick fills it each tick.
	for _i in 80:
		log.append({
			"focus": "",
			"region_members": {"spout:stream": ["jug"]},
		})
	return log


## Grab the jug (focus jug + interact), carry a few ticks, throw it.
func _carry_log() -> Array:
	var log: Array = []
	log.append({"focus": "jug", "edges": {"interact": true}})   # grab
	for _i in 5:
		log.append({"focus": ""})                                # carry
	log.append({"focus": "", "edges": {"throw": true}})          # throw releases
	for _i in 3:
		log.append({"focus": ""})
	# Re-grab + drop.
	log.append({"focus": "jug", "edges": {"interact": true}})    # grab again
	log.append({"focus": "", "edges": {"interact": true}})       # held + no place focus -> drop
	for _i in 3:
		log.append({"focus": ""})
	return log


## Full chain A: open valve, fill the jug to full, then place it on the pedestal.
func _chain_a_log() -> Array:
	var log: Array = []
	log.append({"focus": "valve", "edges": {"interact": true}})  # open valve
	# Grab the jug.
	log.append({"focus": "jug", "edges": {"interact": true}})
	# Hold under the stream long enough to fill past full_threshold (0.95). At
	# fill_rate 1.5 * dt(1/60) ≈ 0.025/tick, ~40 ticks fills it; give 80.
	for _i in 80:
		log.append({
			"focus": "",
			"region_members": {"spout:stream": ["jug"]},
		})
	# Carry the (now full) jug to the pedestal and place it (focus pedestal + interact).
	log.append({"focus": "pedestal", "edges": {"interact": true}})
	for _i in 4:
		log.append({"focus": ""})
	return log


## Manually arm the beacon path (place a full jug), then have the player reach the
## beacon region while armed -> trigger. We pre-fill via the same fill chain.
func _armed_reach_log() -> Array:
	var log: Array = _chain_a_log()   # ends with beacon armed
	# Now the player reaches the beacon's reach region.
	for _i in 5:
		log.append({
			"focus": "",
			"player_in_region": {"beacon:reach": true},
		})
	return log


## The converse: the player reaches the beacon WITHOUT arming it -> no trigger.
func _unarmed_reach_log() -> Array:
	var log: Array = []
	for _i in 10:
		log.append({
			"focus": "",
			"player_in_region": {"beacon:reach": true},
		})
	return log


## Place a jug that is NOT full: consumed into the socket, but the guarded
## activation effect is skipped, so pedestal stays inactive and the beacon never arms.
func _place_empty_log() -> Array:
	var log: Array = []
	log.append({"focus": "jug", "edges": {"interact": true}})    # grab empty jug
	log.append({"focus": "pedestal", "edges": {"interact": true}})  # place it
	for _i in 4:
		log.append({"focus": ""})
	# Reach the beacon — must stay inert (pedestal never emitted activated).
	for _i in 5:
		log.append({"focus": "", "player_in_region": {"beacon:reach": true}})
	return log


# ---------------------------------------------------------------------------
# Drive one log across three drivers and compare.
# ---------------------------------------------------------------------------

func _make_kit() -> InteractionKit:
	var kit := InteractionKit.load_from_file(KIT_PATH)
	if not kit.is_valid():
		push_error("golden: invalid kit: %s" % str(kit.load_errors))
	return kit


## Run one driver over the log; return the per-tick state trajectory (deep-copied).
func _record(compiled: bool, log: Array) -> Array:
	var kit := _make_kit()
	var host := ScriptedHost.new()
	var driver = CompiledScript.new() if compiled else InterpScript.new()
	driver.setup(kit, host)
	var tags_of := func(id: String) -> Array:
		var it: InteractionKit.Interactable = kit.interactables.get(id)
		return it.tags if it != null else []
	var traj: Array = []
	for spec: Dictionary in log:
		host.build(spec, tags_of)
		driver.step(DT)
		traj.append(_snapshot(driver, host))
	return traj


## Snapshot the full sim state: every interactable's state record + held id.
func _snapshot(driver, host: ScriptedHost) -> Dictionary:
	var snap := {}
	var states := {}
	for id in driver.state:
		var rec: Dictionary = driver.state[id]
		var copy := {}
		for f in rec:
			copy[f] = rec[f]
		states[id] = copy
	snap["state"] = states
	snap["held"] = host.held_id
	return snap


## Compare two snapshots; return "" if equal else a description of the first diff.
func _diff(a: Dictionary, b: Dictionary) -> String:
	if a["held"] != b["held"]:
		return "held '%s' vs '%s'" % [a["held"], b["held"]]
	var sa: Dictionary = a["state"]
	var sb: Dictionary = b["state"]
	var ids := {}
	for k in sa:
		ids[k] = true
	for k in sb:
		ids[k] = true
	for id in ids:
		var ra: Dictionary = sa.get(id, {})
		var rb: Dictionary = sb.get(id, {})
		var fields := {}
		for f in ra:
			fields[f] = true
		for f in rb:
			fields[f] = true
		for f in fields:
			var va: Variant = ra.get(f, null)
			var vb: Variant = rb.get(f, null)
			if not _val_eq(va, vb):
				return "%s.%s = %s vs %s" % [id, f, str(va), str(vb)]
	return ""


func _val_eq(a: Variant, b: Variant) -> bool:
	if typeof(a) == TYPE_FLOAT or typeof(b) == TYPE_FLOAT:
		return absf(float(a) - float(b)) <= EPS
	return a == b


func _max_delta(a: Dictionary, b: Dictionary) -> float:
	var d := 0.0
	var sa: Dictionary = a["state"]
	var sb: Dictionary = b["state"]
	for id in sa:
		var ra: Dictionary = sa[id]
		var rb: Dictionary = sb.get(id, {})
		for f in ra:
			if typeof(ra[f]) == TYPE_FLOAT and rb.has(f) and typeof(rb[f]) == TYPE_FLOAT:
				d = maxf(d, absf(float(ra[f]) - float(rb[f])))
	return d


func _compare(a: Array, b: Array) -> Dictionary:
	var first_div := ""
	var div_tick := -1
	var max_delta := 0.0
	var n: int = mini(a.size(), b.size())
	for t in n:
		max_delta = maxf(max_delta, _max_delta(a[t], b[t]))
		if first_div == "":
			var d := _diff(a[t], b[t])
			if d != "":
				first_div = d
				div_tick = t
	if first_div == "" and a.size() != b.size():
		first_div = "trajectory length %d vs %d" % [a.size(), b.size()]
	return {"div": first_div, "tick": div_tick, "max_delta": max_delta}


func _run_case(case: Dictionary) -> void:
	var case_name: String = case["name"]
	var log: Array = case["log"]
	var traj_interp := _record(false, log)
	var traj_compiled := _record(true, log)
	var traj_repeat := _record(false, log)

	var ec := _compare(traj_interp, traj_compiled)
	var rep := _compare(traj_interp, traj_repeat)

	_assert(
		"[%s] interpreter == compiled over %d ticks" % [case_name, log.size()],
		ec["div"] == "",
		"max_delta=%s%s" % [String.num(ec["max_delta"], 9),
			"" if ec["div"] == "" else (", FIRST DIVERGENCE @tick %d: %s" % [ec["tick"], ec["div"]])]
	)
	_assert(
		"[%s] interpreter == interpreter-repeat (determinism) over %d ticks" % [case_name, log.size()],
		rep["div"] == "",
		"identical" if rep["div"] == "" else ("FIRST DIVERGENCE @tick %d: %s" % [rep["tick"], rep["div"]])
	)

	# Non-vacuity: the interpreter's FINAL tick must reach the expected terminal
	# state (proves the chain actually fired; equivalence alone could pass on a no-op).
	if traj_interp.size() > 0:
		var final: Dictionary = traj_interp[traj_interp.size() - 1]
		if case.has("expect"):
			var ok := true
			var why := ""
			for id in case["expect"]:
				var want: Dictionary = case["expect"][id]
				var got: Dictionary = final["state"].get(id, {})
				for f in want:
					if not _val_eq(got.get(f, null), want[f]):
						ok = false
						why = "%s.%s = %s (want %s)" % [id, f, str(got.get(f, null)), str(want[f])]
			_assert("[%s] reaches expected terminal state (non-vacuous)" % case_name, ok,
				"reached" if ok else why)
		if case.has("expect_held"):
			_assert("[%s] final carry id as expected" % case_name,
				final["held"] == case["expect_held"],
				"held='%s' want='%s'" % [final["held"], case["expect_held"]])


func _assert(test_name: String, condition: bool, evidence: String) -> void:
	if condition:
		_pass += 1
		print("  PASS  %s  [%s]" % [test_name, evidence])
	else:
		_fail += 1
		print("  FAIL  %s  [%s]" % [test_name, evidence])
