## Body asset converter — MakeHuman CC0 base mesh + macro `.target` morphs → a
## Godot `ArrayMesh` resource with working blendshapes.
##
## This is the §1 pipeline of docs/decisions/body-and-locomotion-slice.md:
## direct `.target`-ASCII parsing (NOT headless Blender / MPFB). The input is
## pure text (OBJ + ASCII sparse vertex-delta `.target` files), all CC0 from the
## pinned MakeHuman source (makehumancommunity/makehuman v1.3.0). The output is a
## deterministic, byte-stable `ArrayMesh` carrying the base mesh + one blendshape
## per selected macro axis anchor.
##
## Run headless (windowed under xvfb per the project's verification posture):
##   MAKEHUMAN_SRC=/path/to/makehuman/source \
##   xvfb-run -a godot4 --path . res://tools/body_converter.tscn --quit-after 600
##
## In the nix derivation the MAKEHUMAN_SRC env var points at the pinned
## fetchFromGitHub store path; in a dev run it points at the prefetched source.
## If MAKEHUMAN_SRC is unset, falls back to a `makehuman/` dir at the repo root.
##
## Outputs (committed, regenerated by `nix build .#body-assets`):
##   res://assets/body/base_body.res        — ArrayMesh + blendshapes + LBS skin
##                                             (ARRAY_BONES/ARRAY_WEIGHTS from the
##                                             CC0 default_weights.mhw)
##   res://assets/body/base_body.manifest.json — axis → blendshape index map +
##                                             rig metadata + provenance
##   res://assets/body/base_body_rig.json   — Slice 3 rig data (bone tree + rest
##                                             transforms from default.mhskel joint
##                                             cubes); scripts/body/body_rig.gd
##                                             reconstructs Skeleton3D + Skin from
##                                             it at runtime (byte-deterministic;
##                                             avoids PackedScene's random IDs).
##
## Determinism: vertices in OBJ order, quads triangulated with a fixed diagonal
## (v0-v1-v2, v0-v2-v3) in stable face order, sparse deltas scattered onto a
## zero base in ascending vertex-index order. Same pinned input → identical mesh.
extends Node

## MakeHuman → meters. base.obj spans ~16.94 MH units head-to-toe; × 0.1 ≈ 1.69 m,
## a real adult height (units-and-scale.md: 1u = 1m, ~1.7–1.8 m adult).
const MH_TO_METERS := 0.1

const OUT_DIR := "res://assets/body"
const OUT_MESH := "res://assets/body/base_body.res"
const OUT_MANIFEST := "res://assets/body/base_body.manifest.json"

## Slice 3 — the rig data for the skinned, posable body. Emitted as DETERMINISTIC
## JSON (not a PackedScene: Godot's PackedScene serializer assigns random
## local-subresource IDs, which would break byte-reproducibility). The JSON
## carries the bone hierarchy + rest/bind transforms derived from the vendored
## CC0 default.mhskel (joint cubes) + the bone order matching the ARRAY_BONES
## indices baked into base_body.res from default_weights.mhw. scripts/body/
## body_rig.gd builds a Skeleton3D + skinned MeshInstance3D from base_body.res +
## this JSON at runtime — fully reproducible, no random IDs. CC0 throughout.
const OUT_RIGGED := "res://assets/body/base_body_rig.json"

## Max bone influences per vertex Godot's LBS supports (ARRAY_BONES/ARRAY_WEIGHTS
## are 4-wide). MakeHuman ships more per vertex; we keep the top-4 and renormalize.
const MAX_INFLUENCES := 4

## The macro axis anchors imported as blendshapes for Slice 1. Each entry is a
## clean CC0 anchor `.target` (relative to <src>/makehuman/data/targets/) whose
## sparse deltas displace the base mesh along ONE macro axis. AGE is mandatory
## (it feeds the §2.2 NSFW gate); gender / muscle / weight / height accompany it.
## (MakeHuman stores age/gender as race-keyed combination targets — the base mesh
## is the caucasian, ~50%-gender, young, average-everything anchor — so the age
## and gender axes are anchored on the caucasian young/old/baby/child + male
## targets, which is the documented MakeHuman macro layout.)
const AXIS_TARGETS := [
	# axis name           # .target path under data/targets/
	["age_old",    "macrodetails/caucasian-female-old.target"],
	["age_baby",   "macrodetails/caucasian-female-baby.target"],
	["age_child",  "macrodetails/caucasian-female-child.target"],
	["gender_male", "macrodetails/caucasian-male-young.target"],
	["muscle_max", "macrodetails/universal-female-young-maxmuscle-averageweight.target"],
	["weight_max", "macrodetails/universal-female-young-averagemuscle-maxweight.target"],
	["height_max", "macrodetails/height/female-young-averagemuscle-averageweight-maxheight.target"],
	# PROPORTIONS is a BIDIRECTIONAL macro in MakeHuman (like height's min/max): the
	# base mesh is the AVERAGE-proportions anchor and there are two opposite targets,
	# "idealproportions" and "uncommonproportions", keyed by the same age/muscle/weight
	# choice as the other macro anchors (female-young-averagemuscle-averageweight). We
	# import BOTH so the BodyState proportions axis can drive from uncommon(0) through
	# the average base(0.5) to ideal(1) — see BodyState.to_blend_weights().
	["proportions_ideal",   "macrodetails/proportions/female-young-averagemuscle-averageweight-idealproportions.target"],
	["proportions_uncommon", "macrodetails/proportions/female-young-averagemuscle-averageweight-uncommonproportions.target"],
]


func _ready() -> void:
	var code := _run()
	get_tree().quit(code)


func _src_root() -> String:
	var env := OS.get_environment("MAKEHUMAN_SRC")
	if env != "":
		return env.path_join("makehuman").path_join("data") if not env.ends_with("data") else env
	# fallback: vendored CC0 subset (vendor/makehuman-cc0/data/) — works on any
	# platform with only Godot, no fetch, no nix. Same v1.3.0 content as the nix
	# derivation's pinned fetchFromGitHub source → byte-identical output.
	return ProjectSettings.globalize_path("res://vendor/makehuman-cc0/data")


func _run() -> int:
	var data_root := _src_root()
	print("body_converter: data root = %s" % data_root)

	var obj_path := data_root.path_join("3dobjs/base.obj")
	var parsed := _parse_obj(obj_path)
	if parsed.is_empty():
		push_error("body_converter: failed to parse %s" % obj_path)
		return 1

	var base_verts: PackedVector3Array = parsed["base_verts"]   # MH-space, raw, ALL `v`
	var render_pos: PackedVector3Array = parsed["render_pos"]   # MH-space, raw, per render vert
	var render_uv: PackedVector2Array = parsed["render_uv"]     # UV per render vert
	var render_to_base: PackedInt32Array = parsed["render_to_base"]  # render vert -> base `v`
	var tris: PackedInt32Array = parsed["tris"]                 # indices into render verts
	var n := base_verts.size()                                  # base vertex count (morph/skin keyed by this)
	var rn := render_pos.size()                                 # render vertex count (expanded at UV seams)
	var body_vert_count: int = parsed["body_vert_count"]
	print("body_converter: %d base verts (%d body), %d render verts (corner-expanded), %d triangle indices (%d tris)" % [n, body_vert_count, rn, tris.size(), tris.size() / 3])

	# --- scale + feet-to-origin transform (1u = 1m) ---------------------------
	# Lift so the lowest BODY vertex (feet) sits at y=0. Using only body verts keeps
	# helper-* proxies (e.g. the skirt hanging below the feet) from offsetting the
	# rendered body off the floor; the rig shares this same min_y (one frame).
	var min_y := INF
	for i in body_vert_count:
		min_y = min(min_y, base_verts[i].y)
	# scaled RENDER positions, lifted so the lowest vertex (feet) sits at y = 0
	var scaled_render := PackedVector3Array()
	scaled_render.resize(rn)
	for i in rn:
		var v := render_pos[i]
		scaled_render[i] = Vector3(v.x * MH_TO_METERS, (v.y - min_y) * MH_TO_METERS, v.z * MH_TO_METERS)

	# --- normals from the triangulated render mesh (smooth, deterministic) ----
	var normals := _compute_normals(scaled_render, tris)

	# --- rig: parse the vendored CC0 skeleton + per-vertex skin weights -------
	# (Slice 3, §1.5 / §3.) The .mhskel gives the bone hierarchy + joint cubes
	# (joint name -> base-mesh vertex indices whose CENTROID is the joint position),
	# all derivable from the SAME base.obj we already parsed. default_weights.mhw
	# gives per-vertex bone weights. Both are CC0, vendored, deterministic.
	var skel_path := data_root.path_join("rigs/default.mhskel")
	var rig := _parse_skeleton(skel_path, base_verts, min_y)   # base_verts: raw MH-space
	if rig.is_empty():
		push_error("body_converter: failed to parse skeleton %s" % skel_path)
		return 1
	var bone_names: PackedStringArray = rig["bone_names"]
	print("body_converter: skeleton with %d bones" % bone_names.size())

	var weights_path := data_root.path_join("rigs/default_weights.mhw")
	# Returns ARRAY_BONES (PackedInt32Array, 4 per vertex) + ARRAY_WEIGHTS
	# (PackedFloat32Array, 4 per vertex), top-4 influences, renormalized.
	var skin_arrays := _parse_weights(weights_path, rig["name_to_index"], n)
	if skin_arrays.is_empty():
		push_error("body_converter: failed to parse skin weights %s" % weights_path)
		return 1
	var base_bones_arr: PackedInt32Array = skin_arrays["bones"]      # 4 per BASE vert
	var base_weights_arr: PackedFloat32Array = skin_arrays["weights"]
	print("body_converter: skin weights for %d base verts (%d unweighted -> root)" % [n, skin_arrays["unweighted"]])

	# --- expand skin weights onto render verts via render_to_base -------------
	# ARRAY_BONES/ARRAY_WEIGHTS are keyed PER RENDER VERTEX; the parsed weights are
	# keyed per BASE vertex. Each render vert that came from base vert b copies b's
	# 4-wide influence set, so a UV-seam split shares its parent's skinning exactly.
	var bones_arr := PackedInt32Array()
	var weights_arr := PackedFloat32Array()
	bones_arr.resize(rn * MAX_INFLUENCES)
	weights_arr.resize(rn * MAX_INFLUENCES)
	for ri in rn:
		var b := render_to_base[ri]
		var ro := ri * MAX_INFLUENCES
		var bo := b * MAX_INFLUENCES
		for k in MAX_INFLUENCES:
			bones_arr[ro + k] = base_bones_arr[bo + k]
			weights_arr[ro + k] = base_weights_arr[bo + k]

	# --- build the surface arrays (per RENDER vertex) -------------------------
	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = scaled_render
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_TEX_UV] = render_uv
	arrays[Mesh.ARRAY_INDEX] = tris
	arrays[Mesh.ARRAY_BONES] = bones_arr
	arrays[Mesh.ARRAY_WEIGHTS] = weights_arr

	# --- blendshapes: one per selected macro anchor ---------------------------
	var mesh := ArrayMesh.new()
	# RELATIVE: final = base + Σ(weightᵢ · blend_arrayᵢ); blend arrays are DELTAS.
	mesh.blend_shape_mode = Mesh.BLEND_SHAPE_MODE_RELATIVE
	var manifest_axes := []
	var blend_arrays := []   # one ARRAY for each blendshape, in registration order

	for entry in AXIS_TARGETS:
		var axis_name: String = entry[0]
		var rel: String = entry[1]
		var tpath := data_root.path_join("targets").path_join(rel)
		var deltas := _parse_target(tpath)
		if deltas.is_empty():
			push_error("body_converter: target had no deltas or failed to load: %s" % tpath)
			return 1
		# A blendshape surface array in BLEND_SHAPE_MODE_RELATIVE is the per-vertex
		# DELTA (morphed - base); Godot composes final = base + Σ(weightᵢ · arrayᵢ).
		# (The earlier code stored the ABSOLUTE morphed position here on the false
		# belief that RELATIVE mode subtracts the base internally — it does NOT. At
		# weight 1 that added the whole position again, ~doubling the body's size and
		# lifting it off the floor; that was the creator's "slider changes size" bug.)
		# The `.target` deltas are keyed by BASE vertex index, so we scatter each base
		# delta onto EVERY render vert that came from that base vert (render_to_base)
		# — a UV-seam split moves identically to its parent, keeping morphs watertight
		# across seams. Deltas are MH units, same scale as verts.
		var morphed := scaled_render.duplicate()
		var moved := 0          # render verts displaced
		var moved_base := {}    # distinct BASE verts displaced (for the manifest)
		for ri in rn:
			var b := render_to_base[ri]
			if not deltas.has(b):
				continue
			var d: Vector3 = deltas[b]
			morphed[ri] = morphed[ri] + Vector3(d.x * MH_TO_METERS, d.y * MH_TO_METERS, d.z * MH_TO_METERS)
			moved += 1
			moved_base[b] = true
		# NORMALS — why the blendshape normal array is ZERO, and how correct lighting
		# under morph is actually achieved:
		#
		# Godot 4 stores ALL surface (and blendshape) normals OCTAHEDRAL-COMPRESSED.
		# Octahedral encoding can only represent UNIT directions: it CANNOT carry a
		# normal DELTA. A stored delta is renormalised to a unit vector on encode, so
		#   - true deltas (morphed_normal - base_normal): tiny vectors whose direction
		#     is float noise -> decode to near-random unit vectors -> per-vertex blotchy
		#     dark/bright shading (the "broken normals / inside-out" report);
		#   - any nonzero constant delta (e.g. -base): decodes to a unit vector and pulls
		#     every normal the same way as the weight rises -> blown-out streaks.
		# Verified empirically (true / -base / zero all rendered): there is NO blendshape
		# normal array that yields correct shading, because RELATIVE mode composes
		# final = base + Σ wᵢ·Δnᵢ and octa can't encode the deltas. Godot also REQUIRES
		# the blendshape format to match the surface (which has normals), so the array
		# can't be omitted ("Blend shape format must match the main array format").
		#
		# Therefore we store a ZERO normal delta (the least-wrong GPU value: keeps the
		# base normals) and recompute the morphed normals ON THE CPU when morphs change
		# — see BodyState.bake_morphed_normals() / CharacterCreator. The accurate data
		# lives in the VERTEX deltas (positions aren't unit-constrained, so they encode
		# faithfully); from base + Σ wᵢ·Δvᵢ the CPU derives exact per-vertex normals and
		# writes them back, giving correct lighting at every weight. (UVs are likewise
		# NOT stored per blendshape — corner-expansion already gave the surface UVs.)
		var vert_delta := PackedVector3Array()
		var norm_delta := PackedVector3Array()
		vert_delta.resize(rn)
		norm_delta.resize(rn)   # zero-initialised -> zero normal deltas (see note above)
		for vi in rn:
			vert_delta[vi] = morphed[vi] - scaled_render[vi]
		var ba := []
		ba.resize(Mesh.ARRAY_MAX)
		ba[Mesh.ARRAY_VERTEX] = vert_delta
		ba[Mesh.ARRAY_NORMAL] = norm_delta
		mesh.add_blend_shape(axis_name)
		blend_arrays.append(ba)
		manifest_axes.append({
			"axis": axis_name,
			"blend_shape_index": manifest_axes.size(),
			"source_target": "targets/" + rel,
			"moved_vertices": moved_base.size(),
		})
		print("body_converter: blendshape '%s' <- %s (%d base verts moved, %d render verts)" % [axis_name, rel, moved_base.size(), moved])

	# add the surface with all blendshapes attached
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays, blend_arrays)
	mesh.surface_set_name(0, "body")

	# --- write outputs --------------------------------------------------------
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var err := ResourceSaver.save(mesh, OUT_MESH, ResourceSaver.FLAG_COMPRESS)
	if err != OK:
		push_error("body_converter: failed to save mesh (err %d)" % err)
		return 1
	print("body_converter: wrote %s" % OUT_MESH)

	var manifest := {
		"_comment": "Generated by tools/body_converter.gd from MakeHuman CC0 source. DO NOT hand-edit; regenerate with `nix build .#body-assets`.",
		"license": "CC0-1.0 (MakeHuman core base mesh + targets, explicitly CC0 since Sept 2020)",
		"source": {
			"owner": "makehumancommunity",
			"repo": "makehuman",
			"rev": "v1.3.0",
			"sha256": "sha256-x0v/SkwtOl1lkVi2TRuIgx2Xgz4JcWD3He7NhU44Js4=",
		},
		"mh_to_meters": MH_TO_METERS,
		"vertex_count": n,
		"render_vertex_count": rn,
		"triangle_count": tris.size() / 3,
		"axes": manifest_axes,
		"rig": {
			"skeleton": "rigs/default.mhskel",
			"weights": "rigs/default_weights.mhw",
			"weights_license": "CC0 (MakeHuman default_weights.mhw, symmetric weights for the default mesh)",
			"bone_count": bone_names.size(),
			"max_influences": MAX_INFLUENCES,
			"rigged_scene": OUT_RIGGED,
			"unweighted_vertices": skin_arrays["unweighted"],
		},
	}
	var mf := FileAccess.open(OUT_MANIFEST, FileAccess.WRITE)
	if mf == null:
		push_error("body_converter: cannot write manifest")
		return 1
	mf.store_string(JSON.stringify(manifest, "\t"))
	mf.flush()
	mf.close()
	print("body_converter: wrote %s" % OUT_MANIFEST)

	# --- write the deterministic rig data JSON --------------------------------
	if not _write_rig_data(rig):
		push_error("body_converter: failed to write rig data")
		return 1
	print("body_converter: wrote %s" % OUT_RIGGED)

	print("body_converter: DONE")
	return 0


# ---------------------------------------------------------------------------
# Rig + skin (Slice 3). Skeleton3D from the .mhskel joint cubes; skin weights
# from default_weights.mhw. All CC0, vendored, deterministic.
# ---------------------------------------------------------------------------

## Parse default.mhskel: bone hierarchy + the `joints` map (joint name -> list of
## base-mesh vertex indices; the joint POSITION is the centroid of those verts —
## MakeHuman's "joint cube" scheme). Each bone's head/tail are named joints; the
## bone's rest position is its head. We emit, in a DETERMINISTIC order (bones
## sorted parent-before-child, ties by name), the data needed to build a
## Skeleton3D: bone name, parent index, and rest transform (origin at head, in
## the SAME scaled+feet-lifted mesh space as the render mesh).
##
## `base_verts` are RAW MH-space vertices; `min_y` the raw min — we apply the
## identical MH_TO_METERS scale + feet-to-origin lift the mesh uses, so bones and
## skin live in one coordinate frame.
func _parse_skeleton(path: String, base_verts: PackedVector3Array, min_y: float) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open skeleton %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var text := f.get_as_text()
	f.close()
	var data = JSON.parse_string(text)
	if typeof(data) != TYPE_DICTIONARY or not data.has("bones") or not data.has("joints"):
		push_error("body_converter: malformed mhskel")
		return {}
	var bones: Dictionary = data["bones"]
	var joints: Dictionary = data["joints"]

	# Resolve a joint name -> world (scaled+lifted) position via vertex centroid.
	var joint_pos := func(jname: String) -> Vector3:
		var idxs = joints.get(jname, null)
		if idxs == null or (idxs is Array and idxs.is_empty()):
			return Vector3.ZERO
		var acc := Vector3.ZERO
		for vi in idxs:
			var v: Vector3 = base_verts[int(vi)]
			acc += v
		acc /= float(idxs.size())
		# same transform as the render mesh: scale + lift feet to y=0
		return Vector3(acc.x * MH_TO_METERS, (acc.y - min_y) * MH_TO_METERS, acc.z * MH_TO_METERS)

	# Deterministic topological order: parents before children, name-sorted ties.
	var all_names := bones.keys()
	all_names.sort()   # stable alpha order baseline
	var ordered := PackedStringArray()
	var placed := {}
	# repeatedly append any not-yet-placed bone whose parent is placed (or null/root)
	var progressed := true
	while progressed and ordered.size() < all_names.size():
		progressed = false
		for bname in all_names:
			if placed.has(bname):
				continue
			var parent = bones[bname].get("parent", null)
			if parent == null or placed.has(parent):
				ordered.append(bname)
				placed[bname] = true
				progressed = true
	# defensive: append any stragglers (shouldn't happen with a well-formed tree)
	for bname in all_names:
		if not placed.has(bname):
			ordered.append(bname)

	var name_to_index := {}
	for i in ordered.size():
		name_to_index[ordered[i]] = i

	# Rest transforms: bone origin = head joint position, in GLOBAL mesh space.
	# We store global rests; the scene builder converts to bone-local via parent.
	var global_rest := []        # Transform3D per bone (origin = head, basis = identity)
	var parent_index := PackedInt32Array()
	var tails := []              # tail global pos per bone (for orientation/debug)
	for i in ordered.size():
		var bname := ordered[i]
		var bdef: Dictionary = bones[bname]
		var head: Vector3 = joint_pos.call(bdef.get("head", ""))
		var tail: Vector3 = joint_pos.call(bdef.get("tail", ""))
		global_rest.append(Transform3D(Basis.IDENTITY, head))
		tails.append(tail)
		var parent = bdef.get("parent", null)
		parent_index.append(int(name_to_index[parent]) if (parent != null and name_to_index.has(parent)) else -1)

	return {
		"bone_names": ordered,
		"name_to_index": name_to_index,
		"global_rest": global_rest,
		"parent_index": parent_index,
		"tails": tails,
	}


## Parse default_weights.mhw (JSON: { weights: { bone_name: [[vidx, w], ...] } }).
## Emit Godot LBS arrays: ARRAY_BONES (4 ints/vertex) + ARRAY_WEIGHTS (4 floats/
## vertex), keeping the top-4 influences per vertex and renormalizing to sum 1.
## Bone indices are remapped through name_to_index (the Skeleton3D bone order).
## Unweighted verts fall back to the root bone (index 0 after topo sort) at w=1.
func _parse_weights(path: String, name_to_index: Dictionary, n: int) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open weights %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var data = JSON.parse_string(f.get_as_text())
	f.close()
	if typeof(data) != TYPE_DICTIONARY or not data.has("weights"):
		push_error("body_converter: malformed weights file")
		return {}
	var weights: Dictionary = data["weights"]

	# Accumulate, per vertex, a list of [bone_index, weight] in DETERMINISTIC order
	# (bone names sorted, then vertex order within each bone is the file's order).
	var per_vert := {}    # vidx -> Array of [bidx, w]
	var bnames := weights.keys()
	bnames.sort()
	for bname in bnames:
		if not name_to_index.has(bname):
			continue
		var bidx: int = name_to_index[bname]
		for pair in weights[bname]:
			var vi := int(pair[0])
			var w := float(pair[1])
			if vi < 0 or vi >= n or w <= 0.0:
				continue
			if not per_vert.has(vi):
				per_vert[vi] = []
			per_vert[vi].append([bidx, w])

	var bones_arr := PackedInt32Array()
	var weights_arr := PackedFloat32Array()
	bones_arr.resize(n * MAX_INFLUENCES)
	weights_arr.resize(n * MAX_INFLUENCES)
	var unweighted := 0
	for vi in n:
		var infl = per_vert.get(vi, null)
		var b0 := 0; var b1 := 0; var b2 := 0; var b3 := 0
		var w0 := 0.0; var w1 := 0.0; var w2 := 0.0; var w3 := 0.0
		if infl == null or (infl as Array).is_empty():
			# fall back to root (bone 0) so the vertex is still rigidly carried
			b0 = 0; w0 = 1.0
			unweighted += 1
		else:
			# sort influences by descending weight; ties broken by ascending bone
			# index (deterministic). Keep top-4, renormalize.
			(infl as Array).sort_custom(func(a, b):
				if a[1] != b[1]:
					return a[1] > b[1]
				return a[0] < b[0])
			var top := (infl as Array).slice(0, MAX_INFLUENCES)
			var sum := 0.0
			for e in top:
				sum += e[1]
			if sum <= 0.0:
				b0 = 0; w0 = 1.0
			else:
				var k := top.size()
				if k > 0: b0 = top[0][0]; w0 = top[0][1] / sum
				if k > 1: b1 = top[1][0]; w1 = top[1][1] / sum
				if k > 2: b2 = top[2][0]; w2 = top[2][1] / sum
				if k > 3: b3 = top[3][0]; w3 = top[3][1] / sum
		var o := vi * MAX_INFLUENCES
		bones_arr[o] = b0; bones_arr[o+1] = b1; bones_arr[o+2] = b2; bones_arr[o+3] = b3
		weights_arr[o] = w0; weights_arr[o+1] = w1; weights_arr[o+2] = w2; weights_arr[o+3] = w3

	return {"bones": bones_arr, "weights": weights_arr, "unweighted": unweighted}


## Write deterministic rig data JSON: bone names, parent indices, and each bone's
## GLOBAL rest transform (origin = head joint, in the same scaled+feet-lifted mesh
## space). scripts/body/body_rig.gd reconstructs the Skeleton3D + Skin from this +
## base_body.res at runtime — no PackedScene random IDs, byte-reproducible.
##
## Floats are written via a fixed 6-decimal format so the JSON is byte-stable
## across platforms (avoids float-printing variance). The bone ORDER here is the
## SAME order used to index ARRAY_BONES in base_body.res, so a vertex's bone index
## i refers to bone_names[i] here — one consistent skeleton ordering end to end.
func _write_rig_data(rig: Dictionary) -> bool:
	var bone_names: PackedStringArray = rig["bone_names"]
	var global_rest: Array = rig["global_rest"]
	var parent_index: PackedInt32Array = rig["parent_index"]
	var nb := bone_names.size()

	# Hand-build a stable JSON string (sorted keys, fixed float format) rather than
	# JSON.stringify on floats, so the bytes are identical every rebuild.
	var fmt := func(x: float) -> String: return "%.6f" % x
	var lines := PackedStringArray()
	lines.append("{")
	lines.append("\t\"_comment\": \"Generated by tools/body_converter.gd from CC0 default.mhskel (joint cubes) + default_weights.mhw. DO NOT hand-edit; regenerate with the converter / nix build .#body-assets.\",")
	lines.append("\t\"license\": \"CC0-1.0 (MakeHuman default skeleton + weights)\",")
	lines.append("\t\"bone_count\": %d," % nb)
	lines.append("\t\"bones\": [")
	for i in nb:
		var grest: Transform3D = global_rest[i]
		var o := grest.origin
		var b := grest.basis
		# basis is identity at rest (we author rests as translation-only), but emit
		# it in full for forward-compat / explicitness.
		var row := "\t\t{\"name\": %s, \"parent\": %d, \"head\": [%s, %s, %s], \"basis\": [%s, %s, %s, %s, %s, %s, %s, %s, %s]}" % [
			JSON.stringify(bone_names[i]), parent_index[i],
			fmt.call(o.x), fmt.call(o.y), fmt.call(o.z),
			fmt.call(b.x.x), fmt.call(b.x.y), fmt.call(b.x.z),
			fmt.call(b.y.x), fmt.call(b.y.y), fmt.call(b.y.z),
			fmt.call(b.z.x), fmt.call(b.z.y), fmt.call(b.z.z),
		]
		if i < nb - 1:
			row += ","
		lines.append(row)
	lines.append("\t]")
	lines.append("}")
	var text := "\n".join(lines) + "\n"

	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var f := FileAccess.open(OUT_RIGGED, FileAccess.WRITE)
	if f == null:
		return false
	f.store_string(text)
	f.flush()
	f.close()
	return true


# ---------------------------------------------------------------------------
# Parsers — pure text → arrays. Deterministic: preserve source order.
# ---------------------------------------------------------------------------

## The ONLY OBJ group whose faces are the actual rendered body. MakeHuman's
## base.obj bundles the body mesh with HELPER geometry the rest of the toolchain
## consumes but which must NEVER render: a `helper-*` proxy set (skirt / tights /
## hair / eyes / teeth / tongue / genital / eyelashes — fitting cages for clothing,
## hair and organs) and 125 `joint-*` "joint cubes" (8-vertex boxes whose centroids
## the skeleton fitter reads as joint positions). Including them in the ArrayMesh
## is what made the body render with stray boxes/dots all over it.
##
## We render ONLY `g body` faces. We KEEP the full vertex array — the `joint-*`
## cube vertices (read by index via the .mhskel `joints` map in _parse_skeleton)
## and every blendshape/skin-weight vertex index stay valid and unchanged; the
## helper/joint vertices simply become unreferenced by the rendered index buffer.
const BODY_GROUP := "body"

## Parse a MakeHuman base.obj into a RENDER mesh via OBJ corner-expansion.
##
## OBJ stores positions (`v`), texture coords (`vt`), and faces whose corners are
## `v/vt` index pairs. A correct OBJ→engine import must produce ONE render vertex
## per unique `(v, vt)` corner: a base position referenced under several distinct
## `vt` indices (a UV seam) becomes several render vertices, each with its own UV.
## Indexing UVs by the position index alone (or omitting UVs entirely, the bug
## this replaced) smears the texture across seams. This mesh HAS seams — base.obj
## has 21334 `vt` for 19158 `v` — so corner-expansion is mandatory.
##
## We render ONLY `g body` faces (see BODY_GROUP); helper-* / joint-* faces are
## skipped so their geometry never renders. Quads (a b c d) triangulate to
## (a b c) + (a c d) with a fixed diagonal. OBJ indices are 1-based.
##
## Returns:
##   render_pos       PackedVector3Array  — RAW MH-space position per render vert
##   render_uv        PackedVector2Array  — UV per render vert (OBJ vt; v flipped
##                                          to Godot's top-left origin)
##   render_to_base   PackedInt32Array    — render vert -> base `v` index (0-based)
##   tris             PackedInt32Array     — triangle indices into the render verts
##   base_vert_count  int                  — full base `v` count (morph/skin/joint
##                                           indices are keyed by THIS, unchanged)
##   body_vert_count  int                  — leading base verts in the rendered body
func _parse_obj(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open OBJ %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var base_verts := PackedVector3Array()   # all `v`, file order (morph/skin/joint keyed by this)
	var uvs := PackedVector2Array()           # all `vt`, file order
	var render_pos := PackedVector3Array()    # one per unique (v,vt) corner
	var render_uv := PackedVector2Array()
	var render_to_base := PackedInt32Array()
	var tris := PackedInt32Array()
	# (v_idx, vt_idx) corner -> render-vertex index. Keyed by a stable composite int
	# so identical corners across faces share one render vertex (deterministic).
	var corner_to_render := {}
	var in_body := false   # are we inside the `g body` group right now?
	var body_faces := 0
	var body_base_vmax := -1   # highest BASE vertex index referenced by a body face

	# Resolve a face corner token "v/vt[/vn]" to a render-vertex index, creating one
	# on first sight of a (v,vt) pair. Missing vt (e.g. "v" or "v//vn") falls back to
	# the position index as the UV key with a zero UV (defensive; not present here).
	var corner := func(tok: String) -> int:
		var parts := tok.split("/")
		var vi := int(parts[0].to_int() - 1)   # 1-based -> 0-based base vertex
		var ti := -1
		if parts.size() >= 2 and parts[1] != "":
			ti = int(parts[1].to_int() - 1)    # 1-based -> 0-based texcoord
		# composite key; +1 so a missing vt (ti=-1 -> 0) never collides with vt 0.
		var key := vi * 2000000 + (ti + 1)
		var existing = corner_to_render.get(key, -1)
		if existing != -1:
			return existing
		var ri := render_pos.size()
		render_pos.append(base_verts[vi])
		# OBJ uses a bottom-left UV origin; Godot samples top-left -> flip V.
		var uv := Vector2(0.0, 0.0)
		if ti >= 0 and ti < uvs.size():
			var raw := uvs[ti]
			uv = Vector2(raw.x, 1.0 - raw.y)
		render_uv.append(uv)
		render_to_base.append(vi)
		corner_to_render[key] = ri
		return ri

	while not f.eof_reached():
		var line := f.get_line()
		if line.begins_with("v "):
			var p := line.split(" ", false)
			base_verts.append(Vector3(p[1].to_float(), p[2].to_float(), p[3].to_float()))
		elif line.begins_with("vt "):
			var p := line.split(" ", false)
			uvs.append(Vector2(p[1].to_float(), p[2].to_float()))
		elif line.begins_with("g "):
			# OBJ group switch: only `g body` faces are part of the rendered body.
			var p := line.split(" ", false)
			in_body = p.size() >= 2 and p[1] == BODY_GROUP
		elif line.begins_with("f "):
			if not in_body:
				continue   # skip helper-* / joint-* faces (non-rendered geometry)
			var p := line.split(" ", false)
			var c := PackedInt32Array()
			for i in range(1, p.size()):
				c.append(corner.call(p[i]))
			if c.size() == 4:
				# quad → 2 tris, fixed diagonal c0-c2
				tris.append(c[0]); tris.append(c[1]); tris.append(c[2])
				tris.append(c[0]); tris.append(c[2]); tris.append(c[3])
				body_faces += 1
			elif c.size() == 3:
				tris.append(c[0]); tris.append(c[1]); tris.append(c[2])
				body_faces += 1
			# (ngons >4 not present in this mesh; ignore defensively)
	f.close()
	if base_verts.is_empty() or body_faces == 0:
		push_error("body_converter: no `g %s` faces found in %s" % [BODY_GROUP, path])
		return {}
	# Leading base verts that belong to the rendered body (the body group is the
	# contiguous leading `v` block in MakeHuman's base.obj). The feet-to-origin lift
	# uses THIS range so helper-* verts (e.g. the skirt below the feet) don't drag
	# the body off the floor. Derived from the base verts actually referenced by the
	# rendered body faces (highest +1). NOTE: computed here, NOT inside the `corner`
	# lambda — a GDScript lambda captures outer locals by value, so an assignment to
	# body_base_vmax inside it would not propagate out.
	for b in render_to_base:
		body_base_vmax = maxi(body_base_vmax, b)
	return {
		"base_verts": base_verts,
		"render_pos": render_pos,
		"render_uv": render_uv,
		"render_to_base": render_to_base,
		"tris": tris,
		"base_vert_count": base_verts.size(),
		"body_vert_count": body_base_vmax + 1,
	}


## Parse a `.target`: comment lines start with '#'; data lines are
## `<vertex_index> <dx> <dy> <dz>` (MakeHuman units). Returns {index: Vector3}.
func _parse_target(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open target %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var out := {}
	while not f.eof_reached():
		var line := f.get_line().strip_edges()
		if line == "" or line.begins_with("#"):
			continue
		var p := line.split(" ", false)
		if p.size() < 4:
			continue
		var idx := p[0].to_int()
		out[idx] = Vector3(p[1].to_float(), p[2].to_float(), p[3].to_float())
	f.close()
	return out


## Smooth per-vertex normals from the triangulated mesh (area-weighted accumulate).
## Deterministic: triangles iterated in index order.
func _compute_normals(verts: PackedVector3Array, tris: PackedInt32Array) -> PackedVector3Array:
	var n := verts.size()
	var normals := PackedVector3Array()
	normals.resize(n)
	for i in n:
		normals[i] = Vector3.ZERO
	var t := 0
	while t < tris.size():
		var a := tris[t]
		var b := tris[t + 1]
		var c := tris[t + 2]
		var fn := (verts[b] - verts[a]).cross(verts[c] - verts[a])
		normals[a] += fn
		normals[b] += fn
		normals[c] += fn
		t += 3
	for i in n:
		var ln := normals[i]
		normals[i] = ln.normalized() if ln.length() > 1e-9 else Vector3.UP
	return normals
