## Body asset converter — MakeHuman CC0 base mesh + macro `.target` morphs → a
## Godot `ArrayMesh` resource with working blendshapes.
##
## This is the §1 pipeline of docs/decisions/body-and-locomotion-slice.md:
## direct `.target`-ASCII parsing (NOT headless Blender / MPFB). The input is
## pure text (OBJ + ASCII sparse vertex-delta `.target` files), all CC0 from the
## pinned MakeHuman source (makehumancommunity/makehuman v1.3.0). The output is a
## deterministic, byte-stable `ArrayMesh` carrying the base mesh + one blendshape
## per selected macro axis anchor.
##
## Run headless (windowed under xvfb per the project's verification posture):
##   MAKEHUMAN_SRC=/path/to/makehuman/source \
##   xvfb-run -a godot4 --path . res://tools/body_converter.tscn --quit-after 600
##
## In the nix derivation the MAKEHUMAN_SRC env var points at the pinned
## fetchFromGitHub store path; in a dev run it points at the prefetched source.
## If MAKEHUMAN_SRC is unset, falls back to a `makehuman/` dir at the repo root.
##
## Outputs (committed, regenerated by `nix build .#body-assets`):
##   res://assets/body/base_body.res        — ArrayMesh + blendshapes + LBS skin
##                                             (ARRAY_BONES/ARRAY_WEIGHTS from the
##                                             CC0 default_weights.mhw)
##   res://assets/body/base_body.manifest.json — axis → blendshape index map +
##                                             rig metadata + provenance
##   res://assets/body/base_body_rig.json   — Slice 3 rig data (bone tree + rest
##                                             transforms from default.mhskel joint
##                                             cubes); scripts/body/body_rig.gd
##                                             reconstructs Skeleton3D + Skin from
##                                             it at runtime (byte-deterministic;
##                                             avoids PackedScene's random IDs).
##
## Determinism: vertices in OBJ order, quads triangulated with a fixed diagonal
## (v0-v1-v2, v0-v2-v3) in stable face order, sparse deltas scattered onto a
## zero base in ascending vertex-index order. Same pinned input → identical mesh.
extends Node

## MakeHuman → meters. base.obj spans ~16.94 MH units head-to-toe; × 0.1 ≈ 1.69 m,
## a real adult height (units-and-scale.md: 1u = 1m, ~1.7–1.8 m adult).
const MH_TO_METERS := 0.1

const OUT_DIR := "res://assets/body"
const OUT_MESH := "res://assets/body/base_body.res"
const OUT_MANIFEST := "res://assets/body/base_body.manifest.json"

## Slice 3 — the rig data for the skinned, posable body. Emitted as DETERMINISTIC
## JSON (not a PackedScene: Godot's PackedScene serializer assigns random
## local-subresource IDs, which would break byte-reproducibility). The JSON
## carries the bone hierarchy + rest/bind transforms derived from the vendored
## CC0 default.mhskel (joint cubes) + the bone order matching the ARRAY_BONES
## indices baked into base_body.res from default_weights.mhw. scripts/body/
## body_rig.gd builds a Skeleton3D + skinned MeshInstance3D from base_body.res +
## this JSON at runtime — fully reproducible, no random IDs. CC0 throughout.
const OUT_RIGGED := "res://assets/body/base_body_rig.json"

## Max bone influences per vertex Godot's LBS supports (ARRAY_BONES/ARRAY_WEIGHTS
## are 4-wide). MakeHuman ships more per vertex; we keep the top-4 and renormalize.
const MAX_INFLUENCES := 4

## The parsed .mhskel `joints` map (joint name -> base-vertex-index list), stashed by
## _parse_skeleton so the soft-region reweight can recompute joint centroids in RAW MH
## space (the body verts' space) for deterministic region selection.
var _skel_joints := {}

## The macro axis anchors imported as blendshapes for Slice 1. Each entry is a
## clean CC0 anchor `.target` (relative to <src>/makehuman/data/targets/) whose
## sparse deltas displace the base mesh along ONE macro axis. AGE is mandatory
## (it feeds the §2.2 NSFW gate); gender / muscle / weight / height accompany it.
## (MakeHuman stores age/gender as race-keyed combination targets — the base mesh
## is the caucasian, ~50%-gender, young, average-everything anchor — so the age
## and gender axes are anchored on the caucasian young/old/baby/child + male
## targets, which is the documented MakeHuman macro layout.)
## SLICE B NOTE (data-driven modifier registry, body-parameterization.md §6;
## scripts/body/modifier_registry.gd). This hand-listed 9-entry table is the Slice-1
## shortcut the registry is designed to REPLACE: the registry parses MakeHuman's own
## modifier JSON into 291 modifiers (251 bidirectional, 29 unipolar, 11 macro) with
## kind/range/default/target-paths all derived from data, not retyped here. In Slice C
## this table is SUBSUMED — the macro axes (gender/age/muscle/weight/height/proportions)
## become the registry's `kind=="macro"` entries driving the §1.3 factor-product cube,
## and the detail axes become the registry's bidirectional/unipolar entries imported as
## blendshapes keyed by their target file path (the same names BodyState._project_modifiers
## already emits). Slice B does NOT touch this path: base_body.res stays byte-unchanged and
## the registry is built into a SEPARATE artifact (assets/body/modifier_registry.json) by
## tools/modifier_registry_build.gd. The macro registry entries reconcile with these axes
## thus: macrodetails/Gender -> gender_male, macrodetails/Age -> age_baby/child/old fan-out,
## macrodetails-universal/{Muscle,Weight} -> muscle_max/weight_max,
## macrodetails-height/Height -> height_max, macrodetails-proportions/BodyProportions ->
## proportions_ideal/uncommon (BodyState.to_blend_weights() already owns this projection).
const AXIS_TARGETS := [
	# axis name           # .target path under data/targets/
	["age_old",    "macrodetails/caucasian-female-old.target"],
	["age_baby",   "macrodetails/caucasian-female-baby.target"],
	["age_child",  "macrodetails/caucasian-female-child.target"],
	["gender_male", "macrodetails/caucasian-male-young.target"],
	["muscle_max", "macrodetails/universal-female-young-maxmuscle-averageweight.target"],
	["weight_max", "macrodetails/universal-female-young-averagemuscle-maxweight.target"],
	["height_max", "macrodetails/height/female-young-averagemuscle-averageweight-maxheight.target"],
	# PROPORTIONS is a BIDIRECTIONAL macro in MakeHuman (like height's min/max): the
	# base mesh is the AVERAGE-proportions anchor and there are two opposite targets,
	# "idealproportions" and "uncommonproportions", keyed by the same age/muscle/weight
	# choice as the other macro anchors (female-young-averagemuscle-averageweight). We
	# import BOTH so the BodyState proportions axis can drive from uncommon(0) through
	# the average base(0.5) to ideal(1) — see BodyState.to_blend_weights().
	["proportions_ideal",   "macrodetails/proportions/female-young-averagemuscle-averageweight-idealproportions.target"],
	["proportions_uncommon", "macrodetails/proportions/female-young-averagemuscle-averageweight-uncommonproportions.target"],
]

## FACIAL EXPRESSION blendshapes (the channel-geometry that closes the FaceRig gap).
##
## MakeHuman v1.3.0 ships CC0 FACS-like "action unit" expression targets under
## data/targets/expression/units/<race>/ (verified explicitly CC0 — LICENSE.md §C
## "Targets", LICENSE.ASSETS.md "# Creative Commons CC0 1.0 Universal"; same `.target`
## ASCII sparse-delta format as the macro anchors above, keyed by BASE vertex index).
## We import the CAUCASIAN unit set (the same race anchor the base mesh uses) and
## COMPOSE the per-side units into the FaceRig's channel-named blendshapes, so each
## resolved channel (scripts/body/face/face_rig.gd val_*) has geometry to drive.
##
## Each entry: [blendshape name == FaceRig sink output, [AU target files summed]].
## Summing left+right symmetric units gives a single symmetric channel (the FaceRig
## drives one scalar per channel); the names match FaceRig._drive_head's set() keys.
## These are aeriea's OWN CC0 MakeHuman targets — NO BDCC2 art (Path-A discipline).
##
## COVERAGE (honest): MakeHuman's caucasian unit set is a FACS muscle vocabulary, not
## a 1:1 match for the rig's affect channels. The mapping below is the best faithful
## composition; channels with no faithful AU (MouthBlep — there is no tongue-out AU;
## MouthPanting — no dedicated AU; EyesSexy approximated by the eye-slit AU) are noted.
## Paths are relative to data/targets/ (same root as AXIS_TARGETS).
const EXPR_BLENDSHAPES := [
	# EyesClosed — full lid closure (both eyes). Already bone-drivable (orbicularis);
	# this gives the SKIN/lid geometry the bones can't move on their own.
	["EyesClosed", [
		"expression/units/caucasian/eye-left-closure.target",
		"expression/units/caucasian/eye-right-closure.target"]],
	# EyesSexy — lidded "bedroom"/half-closed eyes. APPROXIMATED by the eye-slit AU
	# (narrowed palpebral fissure); MakeHuman has no dedicated "sultry" unit.
	["EyesSexy", [
		"expression/units/caucasian/eye-left-slit.target",
		"expression/units/caucasian/eye-right-slit.target"]],
	# BrowsShy — inner-brow raise (the worried/shy/sad "AU1" oblique brow).
	["BrowsShy", [
		"expression/units/caucasian/eyebrows-left-inner-up.target",
		"expression/units/caucasian/eyebrows-right-inner-up.target"]],
	# BrowsAngry — brow LOWER/furrow ("AU4").
	["BrowsAngry", [
		"expression/units/caucasian/eyebrows-left-down.target",
		"expression/units/caucasian/eyebrows-right-down.target"]],
	# MouthOpen — jaw-drop mouth opening (supplements the jaw BONE with lip geometry).
	["MouthOpen", ["expression/units/caucasian/mouth-open.target"]],
	# MouthSmile — lip-corner puller (zygomatic, "AU12").
	["MouthSmile", ["expression/units/caucasian/mouth-corner-puller.target"]],
	# MouthSad — lip-corner depressor (frown, "AU15").
	["MouthSad", ["expression/units/caucasian/mouth-depression.target"]],
	# MouthSnarl — upper-lip raise + eversion (sneer, "AU9/10").
	["MouthSnarl", [
		"expression/units/caucasian/mouth-upward-retraction.target",
		"expression/units/caucasian/mouth-eversion.target"]],
	# MouthBlep — no tongue-protrusion AU exists in the CC0 unit set; the closest lip
	# shape is a protrusion+purse (lips pushed forward). APPROXIMATE; not a true blep
	# (a real blep needs the TONGUE proxy, future work). Gives the channel SOME geometry.
	["MouthBlep", [
		"expression/units/caucasian/mouth-protusion.target",
		"expression/units/caucasian/mouth-pursing.target"]],
]


func _ready() -> void:
	var code := _run()
	get_tree().quit(code)


func _src_root() -> String:
	var env := OS.get_environment("MAKEHUMAN_SRC")
	if env != "":
		return env.path_join("makehuman").path_join("data") if not env.ends_with("data") else env
	# fallback: vendored CC0 subset (vendor/makehuman-cc0/data/) — works on any
	# platform with only Godot, no fetch, no nix. Same v1.3.0 content as the nix
	# derivation's pinned fetchFromGitHub source → byte-identical output.
	return ProjectSettings.globalize_path("res://vendor/makehuman-cc0/data")


func _run() -> int:
	var data_root := _src_root()
	print("body_converter: data root = %s" % data_root)

	var obj_path := data_root.path_join("3dobjs/base.obj")
	var parsed := _parse_obj(obj_path)
	if parsed.is_empty():
		push_error("body_converter: failed to parse %s" % obj_path)
		return 1

	var base_verts: PackedVector3Array = parsed["base_verts"]   # MH-space, raw, ALL `v`
	var render_pos: PackedVector3Array = parsed["render_pos"]   # MH-space, raw, per render vert
	var render_uv: PackedVector2Array = parsed["render_uv"]     # UV per render vert
	var render_to_base: PackedInt32Array = parsed["render_to_base"]  # render vert -> base `v`
	var tris: PackedInt32Array = parsed["tris"]                 # indices into render verts
	var n := base_verts.size()                                  # base vertex count (morph/skin keyed by this)
	var rn := render_pos.size()                                 # render vertex count (expanded at UV seams)
	var body_vert_count: int = parsed["body_vert_count"]
	print("body_converter: %d base verts (%d body), %d render verts (corner-expanded), %d triangle indices (%d tris)" % [n, body_vert_count, rn, tris.size(), tris.size() / 3])

	# --- scale + feet-to-origin transform (1u = 1m) ---------------------------
	# Lift so the lowest BODY vertex (feet) sits at y=0. Using only body verts keeps
	# helper-* proxies (e.g. the skirt hanging below the feet) from offsetting the
	# rendered body off the floor; the rig shares this same min_y (one frame).
	var min_y := INF
	for i in body_vert_count:
		min_y = min(min_y, base_verts[i].y)
	# scaled RENDER positions, lifted so the lowest vertex (feet) sits at y = 0
	var scaled_render := PackedVector3Array()
	scaled_render.resize(rn)
	for i in rn:
		var v := render_pos[i]
		scaled_render[i] = Vector3(v.x * MH_TO_METERS, (v.y - min_y) * MH_TO_METERS, v.z * MH_TO_METERS)

	# --- normals from the triangulated render mesh (smooth, deterministic) ----
	# CORRECT BY CONSTRUCTION: normals are accumulated on the UN-SPLIT base topology
	# (via render_to_base) and scattered to the UV-split duplicates, so seam splits
	# share one continuous normal with no reweld step (see _compute_normals).
	var normals := _compute_normals(scaled_render, tris, render_to_base)
	# --- tangents (ARRAY_TANGENT) from UVs ------------------------------------
	# Per-vertex tangent basis (xyz + handedness w), so a skin normal map could be
	# applied later (none ships today — see body_rig material). Computed deterministically
	# (Lengyel), NOT welded across UV seams: a tangent is parameterised by UV, and split
	# corners have distinct UVs, so each side legitimately gets its own tangent.
	var tangents := _compute_tangents(scaled_render, render_uv, tris, normals)

	# --- rig: parse the vendored CC0 skeleton + per-vertex skin weights -------
	# (Slice 3, §1.5 / §3.) The .mhskel gives the bone hierarchy + joint cubes
	# (joint name -> base-mesh vertex indices whose CENTROID is the joint position),
	# all derivable from the SAME base.obj we already parsed. default_weights.mhw
	# gives per-vertex bone weights. Both are CC0, vendored, deterministic.
	var skel_path := data_root.path_join("rigs/default.mhskel")
	var rig := _parse_skeleton(skel_path, base_verts, min_y)   # base_verts: raw MH-space
	if rig.is_empty():
		push_error("body_converter: failed to parse skeleton %s" % skel_path)
		return 1
	var bone_names: PackedStringArray = rig["bone_names"]
	print("body_converter: skeleton with %d bones" % bone_names.size())

	var weights_path := data_root.path_join("rigs/default_weights.mhw")
	# Returns ARRAY_BONES (PackedInt32Array, 4 per vertex) + ARRAY_WEIGHTS
	# (PackedFloat32Array, 4 per vertex), top-4 influences, renormalized.
	var skin_arrays := _parse_weights(weights_path, rig["name_to_index"], n)
	if skin_arrays.is_empty():
		push_error("body_converter: failed to parse skin weights %s" % weights_path)
		return 1
	var base_bones_arr: PackedInt32Array = skin_arrays["bones"]      # 4 per BASE vert
	var base_weights_arr: PackedFloat32Array = skin_arrays["weights"]
	print("body_converter: skin weights for %d base verts (%d unweighted -> root)" % [n, skin_arrays["unweighted"]])

	# --- skin the BELLY + GLUTE soft-region bones onto the body mesh ------------
	# The injected belly/glute bones (above) have no entry in default_weights.mhw, so
	# the body mesh would never deform with them. Here we redirect a fraction of each
	# belly-/glute-region body vertex's weight onto the matching new bone, so the jiggle
	# spring actually moves geometry. Pure geometric selection on the pinned base mesh =>
	# deterministic. (Hair is skinned separately, on the hair proxy surface.)
	var reweighted := _reweight_soft_regions(base_verts, min_y, rig["name_to_index"],
		base_bones_arr, base_weights_arr, body_vert_count)
	print("body_converter: soft-region reweight: belly=%d glute=%d body verts" % [reweighted["belly"], reweighted["glute"]])

	# --- expand skin weights onto render verts via render_to_base -------------
	# ARRAY_BONES/ARRAY_WEIGHTS are keyed PER RENDER VERTEX; the parsed weights are
	# keyed per BASE vertex. Each render vert that came from base vert b copies b's
	# 4-wide influence set, so a UV-seam split shares its parent's skinning exactly.
	var bones_arr := PackedInt32Array()
	var weights_arr := PackedFloat32Array()
	bones_arr.resize(rn * MAX_INFLUENCES)
	weights_arr.resize(rn * MAX_INFLUENCES)
	for ri in rn:
		var b := render_to_base[ri]
		var ro := ri * MAX_INFLUENCES
		var bo := b * MAX_INFLUENCES
		for k in MAX_INFLUENCES:
			bones_arr[ro + k] = base_bones_arr[bo + k]
			weights_arr[ro + k] = base_weights_arr[bo + k]

	# --- build the surface arrays (per RENDER vertex) -------------------------
	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = scaled_render
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_TANGENT] = tangents
	arrays[Mesh.ARRAY_TEX_UV] = render_uv
	arrays[Mesh.ARRAY_INDEX] = tris
	arrays[Mesh.ARRAY_BONES] = bones_arr
	arrays[Mesh.ARRAY_WEIGHTS] = weights_arr

	# --- ARRAY_CUSTOM0: the render-vertex index, baked into the artifact ------
	# The GPU ID-buffer picker (scripts/util/gpu_id_picker.gd) renders the body
	# into an off-screen ID buffer where each fragment carries its source RENDER-
	# VERTEX INDEX (0..rn-1) encoded as a color, decoded back to a vertex on
	# readback. The index is a pure function of vertex count — identical in every
	# body — so it belongs in the asset, not re-derived at load time (which would
	# have to survive every per-instance mesh duplicate + clear_surfaces() re-bake).
	#
	# Channel format: ARRAY_CUSTOM_RGBA8_UNORM. Each render vertex contributes 4
	# bytes (R,G,B,A) — a PackedByteArray of length rn*4. We split the 24-bit index
	# across R/G/B (low/mid/high byte) and leave A=255; the shader reads CUSTOM0 as a
	# normalized vec4 (bytes/255) and the gpu picker reassembles idx = R + G*256 +
	# B*65536 after multiplying each channel by 255 and rounding. 24 bits covers
	# 16.7M verts, far above this mesh's ~14.5k. UNORM (not UINT) so the value round-
	# trips through Godot's standard interpolation/rasteriser as bytes 0..255.
	var custom0 := PackedByteArray()
	custom0.resize(rn * 4)
	for i in rn:
		var o := i * 4
		custom0[o] = i & 0xFF
		custom0[o + 1] = (i >> 8) & 0xFF
		custom0[o + 2] = (i >> 16) & 0xFF
		custom0[o + 3] = 255
	arrays[Mesh.ARRAY_CUSTOM0] = custom0

	# --- ARRAY_CUSTOM1: the render-vertex -> BASE-vertex map, baked into the asset --
	# The normal computation is correct-by-construction by accumulating onto BASE
	# vertices (un-split topology) and scattering to the UV-split render duplicates
	# (see _compute_normals). The runtime CPU re-bake (BodyState.bake_morphed_normals)
	# must use the IDENTICAL mechanism, so it needs render_to_base too — but the runtime
	# only sees base_body.res (an ArrayMesh), not the converter's transient parse. We
	# therefore persist render_to_base IN THE MESH as a second custom channel, same
	# RGBA8_UNORM 24-bit encoding as CUSTOM0: per render vertex, bytes [low, mid, high,
	# 255] of its base index. Base count (~14.5k) is far under 24 bits. This travels
	# with the asset and survives per-instance mesh duplicate + clear_surfaces() re-bake
	# (re-supplied with the same format flags), so converter and runtime agree by
	# construction with NO position-quantization heuristic.
	var custom1 := PackedByteArray()
	custom1.resize(rn * 4)
	for i in rn:
		var bidx := render_to_base[i]
		var o := i * 4
		custom1[o] = bidx & 0xFF
		custom1[o + 1] = (bidx >> 8) & 0xFF
		custom1[o + 2] = (bidx >> 16) & 0xFF
		custom1[o + 3] = 255
	arrays[Mesh.ARRAY_CUSTOM1] = custom1

	# --- blendshapes: one per selected macro anchor ---------------------------
	var mesh := ArrayMesh.new()
	# RELATIVE: final = base + Σ(weightᵢ · blend_arrayᵢ); blend arrays are DELTAS.
	mesh.blend_shape_mode = Mesh.BLEND_SHAPE_MODE_RELATIVE
	var manifest_axes := []
	var blend_arrays := []   # one ARRAY for each blendshape, in registration order

	for entry in AXIS_TARGETS:
		var axis_name: String = entry[0]
		var rel: String = entry[1]
		var tpath := data_root.path_join("targets").path_join(rel)
		var deltas := _parse_target(tpath)
		if deltas.is_empty():
			push_error("body_converter: target had no deltas or failed to load: %s" % tpath)
			return 1
		# A blendshape surface array in BLEND_SHAPE_MODE_RELATIVE is the per-vertex
		# DELTA (morphed - base); Godot composes final = base + Σ(weightᵢ · arrayᵢ).
		# (The earlier code stored the ABSOLUTE morphed position here on the false
		# belief that RELATIVE mode subtracts the base internally — it does NOT. At
		# weight 1 that added the whole position again, ~doubling the body's size and
		# lifting it off the floor; that was the creator's "slider changes size" bug.)
		# The `.target` deltas are keyed by BASE vertex index, so we scatter each base
		# delta onto EVERY render vert that came from that base vert (render_to_base)
		# — a UV-seam split moves identically to its parent, keeping morphs watertight
		# across seams. Deltas are MH units, same scale as verts.
		var morphed := scaled_render.duplicate()
		var moved := 0          # render verts displaced
		var moved_base := {}    # distinct BASE verts displaced (for the manifest)
		for ri in rn:
			var b := render_to_base[ri]
			if not deltas.has(b):
				continue
			var d: Vector3 = deltas[b]
			morphed[ri] = morphed[ri] + Vector3(d.x * MH_TO_METERS, d.y * MH_TO_METERS, d.z * MH_TO_METERS)
			moved += 1
			moved_base[b] = true
		# NORMALS — why the blendshape normal array is ZERO, and how correct lighting
		# under morph is actually achieved:
		#
		# Godot 4 stores ALL surface (and blendshape) normals OCTAHEDRAL-COMPRESSED.
		# Octahedral encoding can only represent UNIT directions: it CANNOT carry a
		# normal DELTA. A stored delta is renormalised to a unit vector on encode, so
		#   - true deltas (morphed_normal - base_normal): tiny vectors whose direction
		#     is float noise -> decode to near-random unit vectors -> per-vertex blotchy
		#     dark/bright shading (the "broken normals / inside-out" report);
		#   - any nonzero constant delta (e.g. -base): decodes to a unit vector and pulls
		#     every normal the same way as the weight rises -> blown-out streaks.
		# Verified empirically (true / -base / zero all rendered): there is NO blendshape
		# normal array that yields correct shading, because RELATIVE mode composes
		# final = base + Σ wᵢ·Δnᵢ and octa can't encode the deltas. Godot also REQUIRES
		# the blendshape format to match the surface (which has normals), so the array
		# can't be omitted ("Blend shape format must match the main array format").
		#
		# Therefore we store a ZERO normal delta (the least-wrong GPU value: keeps the
		# base normals) and recompute the morphed normals ON THE CPU when morphs change
		# — see BodyState.bake_morphed_normals() / CharacterCreator. The accurate data
		# lives in the VERTEX deltas (positions aren't unit-constrained, so they encode
		# faithfully); from base + Σ wᵢ·Δvᵢ the CPU derives exact per-vertex normals and
		# writes them back, giving correct lighting at every weight. (UVs are likewise
		# NOT stored per blendshape — corner-expansion already gave the surface UVs.)
		var vert_delta := PackedVector3Array()
		var norm_delta := PackedVector3Array()
		vert_delta.resize(rn)
		norm_delta.resize(rn)   # zero-initialised -> zero normal deltas (see note above)
		for vi in rn:
			vert_delta[vi] = morphed[vi] - scaled_render[vi]
		var ba := []
		ba.resize(Mesh.ARRAY_MAX)
		ba[Mesh.ARRAY_VERTEX] = vert_delta
		ba[Mesh.ARRAY_NORMAL] = norm_delta
		# Surface now carries ARRAY_TANGENT, so every blendshape must too ("Blend shape
		# format must match the main array format"). Tangent delta is ZERO for the same
		# reason normals are (see octahedral note); the CPU normal re-bake handles shading.
		ba[Mesh.ARRAY_TANGENT] = _zero_tangent_delta(rn)
		mesh.add_blend_shape(axis_name)
		blend_arrays.append(ba)
		manifest_axes.append({
			"axis": axis_name,
			"blend_shape_index": manifest_axes.size(),
			"source_target": "targets/" + rel,
			"moved_vertices": moved_base.size(),
		})
		print("body_converter: blendshape '%s' <- %s (%d base verts moved, %d render verts)" % [axis_name, rel, moved_base.size(), moved])

	# --- facial EXPRESSION blendshapes (close the FaceRig channel gap) ----------
	# Same DELTA/RELATIVE pipeline as the macro anchors above; the only difference is
	# that each channel COMPOSES (sums) one or more CC0 action-unit `.target` files
	# (left+right symmetric units -> one symmetric channel). The resulting blendshape
	# is named EXACTLY as the FaceRig sink's set("blend_shapes/<name>") key, so the
	# rig drives it with no further mapping. Normals stay ZERO deltas for the same
	# octahedral-compression reason as the macros (face morphs are small; the
	# FaceRig drives these as live GPU blendshapes, so per-frame CPU normal re-bake
	# would be too costly — the slight shading staleness under a small face morph is
	# acceptable, and documented in face_rig.gd).
	var expr_axes := []
	for entry in EXPR_BLENDSHAPES:
		var bs_name: String = entry[0]
		var rels: Array = entry[1]
		# Accumulate deltas across all AU files for this channel, keyed by BASE vert.
		var acc := {}    # base vert -> summed Vector3 delta (MH units)
		var missing := false
		for rel2 in rels:
			var tp := data_root.path_join("targets").path_join(String(rel2))
			var ds := _parse_target(tp)
			if ds.is_empty():
				push_error("body_converter: expression target empty/failed: %s" % tp)
				missing = true
				break
			for k in ds:
				acc[k] = acc.get(k, Vector3.ZERO) + ds[k]
		if missing or acc.is_empty():
			push_error("body_converter: expression channel '%s' had no deltas — SKIPPED" % bs_name)
			continue
		# Scatter the summed BASE-keyed deltas onto every render vert (UV-seam-safe,
		# exactly as the macro loop) and build the RELATIVE vertex-delta array.
		var ev_delta := PackedVector3Array()
		var en_delta := PackedVector3Array()
		ev_delta.resize(rn)   # zero-initialised
		en_delta.resize(rn)   # zero normal deltas (see octahedral note above)
		var emoved_base := {}
		for ri in rn:
			var b := render_to_base[ri]
			if not acc.has(b):
				continue
			var d: Vector3 = acc[b]
			ev_delta[ri] = Vector3(d.x * MH_TO_METERS, d.y * MH_TO_METERS, d.z * MH_TO_METERS)
			emoved_base[b] = true
		var eba := []
		eba.resize(Mesh.ARRAY_MAX)
		eba[Mesh.ARRAY_VERTEX] = ev_delta
		eba[Mesh.ARRAY_NORMAL] = en_delta
		eba[Mesh.ARRAY_TANGENT] = _zero_tangent_delta(rn)  # match surface format (see macro loop)
		mesh.add_blend_shape(bs_name)
		blend_arrays.append(eba)
		expr_axes.append({
			"channel": bs_name,
			"blend_shape_index": manifest_axes.size() + expr_axes.size(),
			"source_targets": rels,
			"moved_vertices": emoved_base.size(),
		})
		print("body_converter: expression blendshape '%s' <- %s (%d base verts moved)" % [bs_name, str(rels), emoved_base.size()])

	# add the surface with all blendshapes attached. The CUSTOM0 channel format
	# (ARRAY_CUSTOM_RGBA8_UNORM) must be declared in the format flags or the custom
	# array is ignored — Godot reads the per-custom-channel format from these bits.
	var fmt_flags := Mesh.ARRAY_FORMAT_CUSTOM0 \
		| Mesh.ARRAY_FORMAT_CUSTOM1 \
		| Mesh.ARRAY_FORMAT_TANGENT \
		| (Mesh.ARRAY_CUSTOM_RGBA8_UNORM << Mesh.ARRAY_FORMAT_CUSTOM0_SHIFT) \
		| (Mesh.ARRAY_CUSTOM_RGBA8_UNORM << Mesh.ARRAY_FORMAT_CUSTOM1_SHIFT)
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays, blend_arrays, {}, fmt_flags)
	mesh.surface_set_name(0, "body")

	# --- write outputs --------------------------------------------------------
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var err := ResourceSaver.save(mesh, OUT_MESH, ResourceSaver.FLAG_COMPRESS)
	if err != OK:
		push_error("body_converter: failed to save mesh (err %d)" % err)
		return 1
	print("body_converter: wrote %s" % OUT_MESH)

	var manifest := {
		"_comment": "Generated by tools/body_converter.gd from MakeHuman CC0 source. DO NOT hand-edit; regenerate with `nix build .#body-assets`.",
		"license": "CC0-1.0 (MakeHuman core base mesh + targets, explicitly CC0 since Sept 2020)",
		"source": {
			"owner": "makehumancommunity",
			"repo": "makehuman",
			"rev": "v1.3.0",
			"sha256": "sha256-x0v/SkwtOl1lkVi2TRuIgx2Xgz4JcWD3He7NhU44Js4=",
		},
		"mh_to_meters": MH_TO_METERS,
		"vertex_count": n,
		"render_vertex_count": rn,
		"triangle_count": tris.size() / 3,
		"axes": manifest_axes,
		"expression_blendshapes": expr_axes,
		"rig": {
			"skeleton": "rigs/default.mhskel",
			"weights": "rigs/default_weights.mhw",
			"weights_license": "CC0 (MakeHuman default_weights.mhw, symmetric weights for the default mesh)",
			"bone_count": bone_names.size(),
			"max_influences": MAX_INFLUENCES,
			"rigged_scene": OUT_RIGGED,
			"unweighted_vertices": skin_arrays["unweighted"],
		},
	}
	var mf := FileAccess.open(OUT_MANIFEST, FileAccess.WRITE)
	if mf == null:
		push_error("body_converter: cannot write manifest")
		return 1
	mf.store_string(JSON.stringify(manifest, "\t"))
	mf.flush()
	mf.close()
	print("body_converter: wrote %s" % OUT_MANIFEST)

	# --- write the deterministic rig data JSON --------------------------------
	if not _write_rig_data(rig):
		push_error("body_converter: failed to write rig data")
		return 1
	print("body_converter: wrote %s" % OUT_RIGGED)

	print("body_converter: DONE")
	return 0


# ---------------------------------------------------------------------------
# Rig + skin (Slice 3). Skeleton3D from the .mhskel joint cubes; skin weights
# from default_weights.mhw. All CC0, vendored, deterministic.
# ---------------------------------------------------------------------------

## Parse default.mhskel: bone hierarchy + the `joints` map (joint name -> list of
## base-mesh vertex indices; the joint POSITION is the centroid of those verts —
## MakeHuman's "joint cube" scheme). Each bone's head/tail are named joints; the
## bone's rest position is its head. We emit, in a DETERMINISTIC order (bones
## sorted parent-before-child, ties by name), the data needed to build a
## Skeleton3D: bone name, parent index, and rest transform (origin at head, in
## the SAME scaled+feet-lifted mesh space as the render mesh).
##
## `base_verts` are RAW MH-space vertices; `min_y` the raw min — we apply the
## identical MH_TO_METERS scale + feet-to-origin lift the mesh uses, so bones and
## skin live in one coordinate frame.
func _parse_skeleton(path: String, base_verts: PackedVector3Array, min_y: float) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open skeleton %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var text := f.get_as_text()
	f.close()
	var data = JSON.parse_string(text)
	if typeof(data) != TYPE_DICTIONARY or not data.has("bones") or not data.has("joints"):
		push_error("body_converter: malformed mhskel")
		return {}
	var bones: Dictionary = data["bones"]
	var joints: Dictionary = data["joints"]
	_skel_joints = joints   # stashed for raw-space region selection in the reweight

	# Resolve a joint name -> world (scaled+lifted) position via vertex centroid.
	var joint_pos := func(jname: String) -> Vector3:
		var idxs = joints.get(jname, null)
		if idxs == null or (idxs is Array and idxs.is_empty()):
			return Vector3.ZERO
		var acc := Vector3.ZERO
		for vi in idxs:
			var v: Vector3 = base_verts[int(vi)]
			acc += v
		acc /= float(idxs.size())
		# same transform as the render mesh: scale + lift feet to y=0
		return Vector3(acc.x * MH_TO_METERS, (acc.y - min_y) * MH_TO_METERS, acc.z * MH_TO_METERS)

	# --- inject SECONDARY-MOTION bones (belly / glutes / hair chain) -----------
	# The CC0 default rig has NO belly, glute or hair bones, so the spring-bone layer
	# (scripts/body/spring_bone.gd, resolved BY NAME in body_rig.gd) finds nothing for
	# those regions. We add them HERE — deterministically, from existing joint-cube
	# centroids — so the jiggle/hair springs have bones to drive. Their head/tail are
	# pure functions of the pinned base mesh's joints, so the rig stays byte-stable.
	# Skin weights for these bones are assigned separately (belly/glute onto the body
	# mesh in _reweight_soft_regions; hair onto the hair proxy surface in the proxy
	# builder), since default_weights.mhw knows nothing about them.
	var synth := _synth_soft_bones(joint_pos)
	for sname in synth:
		bones[sname] = synth[sname]

	# Deterministic topological order: parents before children, name-sorted ties.
	var all_names := bones.keys()
	all_names.sort()   # stable alpha order baseline
	var ordered := PackedStringArray()
	var placed := {}
	# repeatedly append any not-yet-placed bone whose parent is placed (or null/root)
	var progressed := true
	while progressed and ordered.size() < all_names.size():
		progressed = false
		for bname in all_names:
			if placed.has(bname):
				continue
			var parent = bones[bname].get("parent", null)
			if parent == null or placed.has(parent):
				ordered.append(bname)
				placed[bname] = true
				progressed = true
	# defensive: append any stragglers (shouldn't happen with a well-formed tree)
	for bname in all_names:
		if not placed.has(bname):
			ordered.append(bname)

	var name_to_index := {}
	for i in ordered.size():
		name_to_index[ordered[i]] = i

	# Rest transforms: bone origin = head joint position, in GLOBAL mesh space.
	# We store global rests; the scene builder converts to bone-local via parent.
	var global_rest := []        # Transform3D per bone (origin = head, basis = identity)
	var parent_index := PackedInt32Array()
	var tails := []              # tail global pos per bone (for orientation/debug)
	for i in ordered.size():
		var bname := ordered[i]
		var bdef: Dictionary = bones[bname]
		# Synthetic secondary-motion bones carry explicit head_pos/tail_pos (already in
		# scaled+lifted render space); the CC0 bones resolve their head/tail by joint name.
		var head: Vector3
		var tail: Vector3
		if bdef.has("head_pos"):
			head = bdef["head_pos"]
			tail = bdef["tail_pos"]
		else:
			head = joint_pos.call(bdef.get("head", ""))
			tail = joint_pos.call(bdef.get("tail", ""))
		global_rest.append(Transform3D(Basis.IDENTITY, head))
		tails.append(tail)
		var parent = bdef.get("parent", null)
		parent_index.append(int(name_to_index[parent]) if (parent != null and name_to_index.has(parent)) else -1)

	return {
		"bone_names": ordered,
		"name_to_index": name_to_index,
		"global_rest": global_rest,
		"parent_index": parent_index,
		"tails": tails,
	}


## Reweight the body mesh's BELLY + GLUTE region vertices onto the injected belly /
## glute.L / glute.R bones so those soft-region jiggle springs actually deform geometry.
##
## DETERMINISTIC + CONSERVATIVE. For each BODY base vertex we compute a smooth 0..1
## membership in the belly region (a forward, midline abdomen band) and each glute
## region (a back, per-side buttock blob), both as falloffs of position within the
## pinned base mesh — a pure function of the geometry. We then move up to MAX_SOFT_W
## of that vertex's weight from its dominant existing bone onto the soft bone, scaled
## by membership, and renormalize the 4-wide influence set. Keeping the transfer a
## FRACTION (not a full reassignment) means the region still rides the torso/hip and
## the spring adds only the soft lag on top — no skin tearing, no over-jiggle.
##
## Mutates base_bones_arr / base_weights_arr in place. Returns moved-vertex counts.
func _reweight_soft_regions(base_verts: PackedVector3Array, min_y: float,
		name_to_index: Dictionary, base_bones_arr: PackedInt32Array,
		base_weights_arr: PackedFloat32Array, body_vert_count: int) -> Dictionary:
	# Max fraction of a vertex's weight transferred to a soft bone at full membership.
	# Conservative so the region keeps most of its rigid skinning (subtle settle).
	const MAX_SOFT_W := 0.6
	var belly_bi: int = name_to_index.get("belly", -1)
	var glute_l_bi: int = name_to_index.get("glute.L", -1)
	var glute_r_bi: int = name_to_index.get("glute.R", -1)
	if belly_bi < 0 or glute_l_bi < 0 or glute_r_bi < 0:
		return {"belly": 0, "glute": 0}

	# Region anchors in RAW MH space (same space as base_verts), from spine/hip joints.
	# Abdomen centre: midpoint of spine04/spine05 head, pushed to the FRONT skin (+Z).
	var sp4 := _raw_joint(base_verts, "spine04____head")
	var sp5 := _raw_joint(base_verts, "spine05____head")
	var pl := _raw_joint(base_verts, "pelvis.L____head")
	var ul := _raw_joint(base_verts, "upperleg01.L____head")
	var pr := _raw_joint(base_verts, "pelvis.R____head")
	var ur := _raw_joint(base_verts, "upperleg01.R____head")
	# A characteristic torso radius (MH units) to scale the region falloffs.
	var torso_r := maxf(absf(sp4.y - sp5.y) * 3.0, 1.0)
	var belly_c := (sp4 + sp5) * 0.5            # abdomen midline centre
	var glute_l_c := (pl + ul) * 0.5            # left hip/leg-root centre
	var glute_r_c := (pr + ur) * 0.5

	var belly_n := 0
	var glute_n := 0
	for v in body_vert_count:
		var p := base_verts[v]
		# BELLY membership: in the abdomen height band, near the midline, on the FRONT
		# (+Z) half. Smooth radial falloff from belly_c plus a front-facing gate.
		var belly_m := 0.0
		var dB := (p - belly_c)
		var radB := Vector3(dB.x, dB.y, 0.0).length()
		if p.z > belly_c.z and radB < torso_r * 1.4:
			belly_m = clampf(1.0 - radB / (torso_r * 1.4), 0.0, 1.0)
			belly_m *= clampf((p.z - belly_c.z) / (torso_r * 0.8), 0.0, 1.0)  # front gate
		# GLUTE membership (per side): in the hip height band, on the BACK (-Z) half,
		# on the correct side. Smooth radial falloff from that side's glute centre.
		var gm_l := 0.0
		var gm_r := 0.0
		if p.z < glute_l_c.z:   # back half
			var dl := (p - glute_l_c)
			if p.x > 0.0:
				var rl := dl.length()
				gm_l = clampf(1.0 - rl / (torso_r * 1.3), 0.0, 1.0)
			else:
				var dr := (p - glute_r_c)
				var rr := dr.length()
				gm_r = clampf(1.0 - rr / (torso_r * 1.3), 0.0, 1.0)
		if belly_m > 0.01:
			_blend_soft_weight(base_bones_arr, base_weights_arr, v, belly_bi, belly_m * MAX_SOFT_W)
			belly_n += 1
		if gm_l > 0.01:
			_blend_soft_weight(base_bones_arr, base_weights_arr, v, glute_l_bi, gm_l * MAX_SOFT_W)
			glute_n += 1
		if gm_r > 0.01:
			_blend_soft_weight(base_bones_arr, base_weights_arr, v, glute_r_bi, gm_r * MAX_SOFT_W)
			glute_n += 1
	return {"belly": belly_n, "glute": glute_n}


## Raw-MH-space joint centroid (no scale/lift) — for region selection in base space.
func _raw_joint(base_verts: PackedVector3Array, jname: String) -> Vector3:
	var idxs = _skel_joints.get(jname, null)
	if idxs == null or (idxs is Array and idxs.is_empty()):
		return Vector3.ZERO
	var acc := Vector3.ZERO
	for vi in idxs:
		acc += base_verts[int(vi)]
	return acc / float(idxs.size())


## Move `amt` (0..1) of vertex v's weight onto soft bone `soft_bi`, taken proportionally
## from the existing influences, then renormalize the 4-wide set. If the soft bone is
## already present its weight is increased; otherwise it replaces the SMALLEST existing
## influence. Deterministic; keeps the influence count at 4. Mutates in place.
func _blend_soft_weight(bones_arr: PackedInt32Array, weights_arr: PackedFloat32Array,
		v: int, soft_bi: int, amt: float) -> void:
	var o := v * MAX_INFLUENCES
	amt = clampf(amt, 0.0, 0.95)
	# Scale down existing influences by (1-amt); the freed mass goes to the soft bone.
	for k in MAX_INFLUENCES:
		weights_arr[o + k] *= (1.0 - amt)
	# If soft bone already in the set, add to it; else replace the smallest-weight slot.
	var slot := -1
	for k in MAX_INFLUENCES:
		if bones_arr[o + k] == soft_bi:
			slot = k
			break
	if slot < 0:
		var min_k := 0
		for k in range(1, MAX_INFLUENCES):
			if weights_arr[o + k] < weights_arr[o + min_k]:
				min_k = k
		slot = min_k
		bones_arr[o + slot] = soft_bi
		weights_arr[o + slot] = 0.0
	weights_arr[o + slot] += amt
	# Renormalize to sum 1 (defensive; the math above already sums to 1).
	var sum := 0.0
	for k in MAX_INFLUENCES:
		sum += weights_arr[o + k]
	if sum > 1e-6:
		for k in MAX_INFLUENCES:
			weights_arr[o + k] /= sum


## Synthetic SECONDARY-MOTION bones not present in the CC0 default rig: a belly bone
## (abdomen soft-region jiggle), a glute bone per side (buttock jiggle), and a 3-link
## hair chain hanging off the head (hair physics). Returns { name: bone_def } where
## each def carries explicit head_pos/tail_pos in the SAME scaled+lifted render space
## the joint_pos callable produces (so the rest transforms compose with the CC0 bones).
##
## Positions are PURE FUNCTIONS of the pinned base mesh's joint cubes — no magic
## numbers beyond fixed anatomical offset fractions — so the emitted rig is byte-stable.
## Names match what scripts/body/body_rig.gd resolves: SOFT_REGION_BONES (belly,
## glute.L, glute.R) and HAIR_BONE_FRAGMENTS ("hair" -> hair01/02/03).
func _synth_soft_bones(joint_pos: Callable) -> Dictionary:
	var sp4: Vector3 = joint_pos.call("spine04____head")   # lower-mid spine
	var sp5: Vector3 = joint_pos.call("spine05____head")   # lowest spine (~pelvis)
	var pl: Vector3 = joint_pos.call("pelvis.L____head")
	var pr: Vector3 = joint_pos.call("pelvis.R____head")
	var ul: Vector3 = joint_pos.call("upperleg01.L____head")
	var ur: Vector3 = joint_pos.call("upperleg01.R____head")
	var head_h: Vector3 = joint_pos.call("head____head")   # base of skull
	var head_t: Vector3 = joint_pos.call("head____tail")   # crown
	# Body faces +Z (front); -Z is the back. A representative torso depth for the
	# forward/back tail offsets, scaled from the spine span so it tracks the mesh size.
	var torso_h := absf(sp4.y - sp5.y)                     # ~0.046 m
	var depth := maxf(torso_h * 1.6, 0.05)                 # soft-region tail reach (m)

	var out := {}
	# BELLY — abdomen, midline, between spine04 and spine05; tail bulges FORWARD+down so
	# the spring tip sits at the navel and swings with body motion. Parent spine04 so it
	# inherits torso motion (the jiggle layer adds the lag on top).
	var belly_head := (sp4 + sp5) * 0.5 + Vector3(0.0, 0.0, depth * 0.4)
	out["belly"] = {
		"parent": "spine04",
		"head_pos": belly_head,
		"tail_pos": belly_head + Vector3(0.0, -depth * 0.5, depth),
	}
	# GLUTES — one per side, anchored between the hip and the upper-leg root; tail points
	# BACK (-Z) + down into the buttock so the spring tip sits on the glute mass. Parent
	# pelvis.<side> so the buttock is carried by the hip.
	var gl_head := (pl + ul) * 0.5
	out["glute.L"] = {
		"parent": "pelvis.L",
		"head_pos": gl_head,
		"tail_pos": gl_head + Vector3(0.0, -depth * 0.5, -depth),
	}
	var gr_head := (pr + ur) * 0.5
	out["glute.R"] = {
		"parent": "pelvis.R",
		"head_pos": gr_head,
		"tail_pos": gr_head + Vector3(0.0, -depth * 0.5, -depth),
	}
	# HAIR — a 3-link chain hanging down the BACK of the scalp from the head bone. The
	# helper-hair cap drapes from the crown (~head tail) down to mid-back; the chain
	# starts at the back of the skull and steps down so the lower links carry the hair
	# tips (where the sway is most visible). Parent: head -> hair01 -> hair02 -> hair03.
	var skull_back := Vector3(0.0, head_t.y, head_h.z - depth * 1.2)  # back of crown
	var hair_span := maxf(head_t.y - head_h.y, 0.1) * 2.0             # reach down the back
	out["hair01"] = {
		"parent": "head",
		"head_pos": skull_back,
		"tail_pos": skull_back + Vector3(0.0, -hair_span * 0.33, -depth * 0.2),
	}
	out["hair02"] = {
		"parent": "hair01",
		"head_pos": skull_back + Vector3(0.0, -hair_span * 0.33, -depth * 0.2),
		"tail_pos": skull_back + Vector3(0.0, -hair_span * 0.66, -depth * 0.35),
	}
	out["hair03"] = {
		"parent": "hair02",
		"head_pos": skull_back + Vector3(0.0, -hair_span * 0.66, -depth * 0.35),
		"tail_pos": skull_back + Vector3(0.0, -hair_span, -depth * 0.5),
	}
	return out


## Parse default_weights.mhw (JSON: { weights: { bone_name: [[vidx, w], ...] } }).
## Emit Godot LBS arrays: ARRAY_BONES (4 ints/vertex) + ARRAY_WEIGHTS (4 floats/
## vertex), keeping the top-4 influences per vertex and renormalizing to sum 1.
## Bone indices are remapped through name_to_index (the Skeleton3D bone order).
## Unweighted verts fall back to the root bone (index 0 after topo sort) at w=1.
func _parse_weights(path: String, name_to_index: Dictionary, n: int) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open weights %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var data = JSON.parse_string(f.get_as_text())
	f.close()
	if typeof(data) != TYPE_DICTIONARY or not data.has("weights"):
		push_error("body_converter: malformed weights file")
		return {}
	var weights: Dictionary = data["weights"]

	# Accumulate, per vertex, a list of [bone_index, weight] in DETERMINISTIC order
	# (bone names sorted, then vertex order within each bone is the file's order).
	var per_vert := {}    # vidx -> Array of [bidx, w]
	var bnames := weights.keys()
	bnames.sort()
	for bname in bnames:
		if not name_to_index.has(bname):
			continue
		var bidx: int = name_to_index[bname]
		for pair in weights[bname]:
			var vi := int(pair[0])
			var w := float(pair[1])
			if vi < 0 or vi >= n or w <= 0.0:
				continue
			if not per_vert.has(vi):
				per_vert[vi] = []
			per_vert[vi].append([bidx, w])

	var bones_arr := PackedInt32Array()
	var weights_arr := PackedFloat32Array()
	bones_arr.resize(n * MAX_INFLUENCES)
	weights_arr.resize(n * MAX_INFLUENCES)
	var unweighted := 0
	for vi in n:
		var infl = per_vert.get(vi, null)
		var b0 := 0; var b1 := 0; var b2 := 0; var b3 := 0
		var w0 := 0.0; var w1 := 0.0; var w2 := 0.0; var w3 := 0.0
		if infl == null or (infl as Array).is_empty():
			# fall back to root (bone 0) so the vertex is still rigidly carried
			b0 = 0; w0 = 1.0
			unweighted += 1
		else:
			# sort influences by descending weight; ties broken by ascending bone
			# index (deterministic). Keep top-4, renormalize.
			(infl as Array).sort_custom(func(a, b):
				if a[1] != b[1]:
					return a[1] > b[1]
				return a[0] < b[0])
			var top := (infl as Array).slice(0, MAX_INFLUENCES)
			var sum := 0.0
			for e in top:
				sum += e[1]
			if sum <= 0.0:
				b0 = 0; w0 = 1.0
			else:
				var k := top.size()
				if k > 0: b0 = top[0][0]; w0 = top[0][1] / sum
				if k > 1: b1 = top[1][0]; w1 = top[1][1] / sum
				if k > 2: b2 = top[2][0]; w2 = top[2][1] / sum
				if k > 3: b3 = top[3][0]; w3 = top[3][1] / sum
		var o := vi * MAX_INFLUENCES
		bones_arr[o] = b0; bones_arr[o+1] = b1; bones_arr[o+2] = b2; bones_arr[o+3] = b3
		weights_arr[o] = w0; weights_arr[o+1] = w1; weights_arr[o+2] = w2; weights_arr[o+3] = w3

	return {"bones": bones_arr, "weights": weights_arr, "unweighted": unweighted}


## Write deterministic rig data JSON: bone names, parent indices, and each bone's
## GLOBAL rest transform (origin = head joint, in the same scaled+feet-lifted mesh
## space). scripts/body/body_rig.gd reconstructs the Skeleton3D + Skin from this +
## base_body.res at runtime — no PackedScene random IDs, byte-reproducible.
##
## Floats are written via a fixed 6-decimal format so the JSON is byte-stable
## across platforms (avoids float-printing variance). The bone ORDER here is the
## SAME order used to index ARRAY_BONES in base_body.res, so a vertex's bone index
## i refers to bone_names[i] here — one consistent skeleton ordering end to end.
func _write_rig_data(rig: Dictionary) -> bool:
	var bone_names: PackedStringArray = rig["bone_names"]
	var global_rest: Array = rig["global_rest"]
	var parent_index: PackedInt32Array = rig["parent_index"]
	var nb := bone_names.size()

	# Hand-build a stable JSON string (sorted keys, fixed float format) rather than
	# JSON.stringify on floats, so the bytes are identical every rebuild.
	var fmt := func(x: float) -> String: return "%.6f" % x
	var lines := PackedStringArray()
	lines.append("{")
	lines.append("\t\"_comment\": \"Generated by tools/body_converter.gd from CC0 default.mhskel (joint cubes) + default_weights.mhw. DO NOT hand-edit; regenerate with the converter / nix build .#body-assets.\",")
	lines.append("\t\"license\": \"CC0-1.0 (MakeHuman default skeleton + weights)\",")
	lines.append("\t\"bone_count\": %d," % nb)
	lines.append("\t\"bones\": [")
	for i in nb:
		var grest: Transform3D = global_rest[i]
		var o := grest.origin
		var b := grest.basis
		# basis is identity at rest (we author rests as translation-only), but emit
		# it in full for forward-compat / explicitness.
		var row := "\t\t{\"name\": %s, \"parent\": %d, \"head\": [%s, %s, %s], \"basis\": [%s, %s, %s, %s, %s, %s, %s, %s, %s]}" % [
			JSON.stringify(bone_names[i]), parent_index[i],
			fmt.call(o.x), fmt.call(o.y), fmt.call(o.z),
			fmt.call(b.x.x), fmt.call(b.x.y), fmt.call(b.x.z),
			fmt.call(b.y.x), fmt.call(b.y.y), fmt.call(b.y.z),
			fmt.call(b.z.x), fmt.call(b.z.y), fmt.call(b.z.z),
		]
		if i < nb - 1:
			row += ","
		lines.append(row)
	lines.append("\t]")
	lines.append("}")
	var text := "\n".join(lines) + "\n"

	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var f := FileAccess.open(OUT_RIGGED, FileAccess.WRITE)
	if f == null:
		return false
	f.store_string(text)
	f.flush()
	f.close()
	return true


# ---------------------------------------------------------------------------
# Parsers — pure text → arrays. Deterministic: preserve source order.
# ---------------------------------------------------------------------------

## The ONLY OBJ group whose faces are the actual rendered body. MakeHuman's
## base.obj bundles the body mesh with HELPER geometry the rest of the toolchain
## consumes but which must NEVER render: a `helper-*` proxy set (skirt / tights /
## hair / eyes / teeth / tongue / genital / eyelashes — fitting cages for clothing,
## hair and organs) and 125 `joint-*` "joint cubes" (8-vertex boxes whose centroids
## the skeleton fitter reads as joint positions). Including them in the ArrayMesh
## is what made the body render with stray boxes/dots all over it.
##
## We render ONLY `g body` faces. We KEEP the full vertex array — the `joint-*`
## cube vertices (read by index via the .mhskel `joints` map in _parse_skeleton)
## and every blendshape/skin-weight vertex index stay valid and unchanged; the
## helper/joint vertices simply become unreferenced by the rendered index buffer.
const BODY_GROUP := "body"

## Parse a MakeHuman base.obj into a RENDER mesh via OBJ corner-expansion.
##
## OBJ stores positions (`v`), texture coords (`vt`), and faces whose corners are
## `v/vt` index pairs. A correct OBJ→engine import must produce ONE render vertex
## per unique `(v, vt)` corner: a base position referenced under several distinct
## `vt` indices (a UV seam) becomes several render vertices, each with its own UV.
## Indexing UVs by the position index alone (or omitting UVs entirely, the bug
## this replaced) smears the texture across seams. This mesh HAS seams — base.obj
## has 21334 `vt` for 19158 `v` — so corner-expansion is mandatory.
##
## We render ONLY `g body` faces (see BODY_GROUP); helper-* / joint-* faces are
## skipped so their geometry never renders. Quads (a b c d) triangulate to
## (a b c) + (a c d) with a fixed diagonal. OBJ indices are 1-based.
##
## Returns:
##   render_pos       PackedVector3Array  — RAW MH-space position per render vert
##   render_uv        PackedVector2Array  — UV per render vert (OBJ vt; v flipped
##                                          to Godot's top-left origin)
##   render_to_base   PackedInt32Array    — render vert -> base `v` index (0-based)
##   tris             PackedInt32Array     — triangle indices into the render verts
##   base_vert_count  int                  — full base `v` count (morph/skin/joint
##                                           indices are keyed by THIS, unchanged)
##   body_vert_count  int                  — leading base verts in the rendered body
func _parse_obj(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open OBJ %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var base_verts := PackedVector3Array()   # all `v`, file order (morph/skin/joint keyed by this)
	var uvs := PackedVector2Array()           # all `vt`, file order
	var render_pos := PackedVector3Array()    # one per unique (v,vt) corner
	var render_uv := PackedVector2Array()
	var render_to_base := PackedInt32Array()
	var tris := PackedInt32Array()
	# (v_idx, vt_idx) corner -> render-vertex index. Keyed by a stable composite int
	# so identical corners across faces share one render vertex (deterministic).
	var corner_to_render := {}
	var in_body := false   # are we inside the `g body` group right now?
	var body_faces := 0
	var body_base_vmax := -1   # highest BASE vertex index referenced by a body face

	# Resolve a face corner token "v/vt[/vn]" to a render-vertex index, creating one
	# on first sight of a (v,vt) pair. Missing vt (e.g. "v" or "v//vn") falls back to
	# the position index as the UV key with a zero UV (defensive; not present here).
	var corner := func(tok: String) -> int:
		var parts := tok.split("/")
		var vi := int(parts[0].to_int() - 1)   # 1-based -> 0-based base vertex
		var ti := -1
		if parts.size() >= 2 and parts[1] != "":
			ti = int(parts[1].to_int() - 1)    # 1-based -> 0-based texcoord
		# composite key; +1 so a missing vt (ti=-1 -> 0) never collides with vt 0.
		var key := vi * 2000000 + (ti + 1)
		var existing = corner_to_render.get(key, -1)
		if existing != -1:
			return existing
		var ri := render_pos.size()
		render_pos.append(base_verts[vi])
		# OBJ uses a bottom-left UV origin; Godot samples top-left -> flip V.
		var uv := Vector2(0.0, 0.0)
		if ti >= 0 and ti < uvs.size():
			var raw := uvs[ti]
			uv = Vector2(raw.x, 1.0 - raw.y)
		render_uv.append(uv)
		render_to_base.append(vi)
		corner_to_render[key] = ri
		return ri

	while not f.eof_reached():
		var line := f.get_line()
		if line.begins_with("v "):
			var p := line.split(" ", false)
			base_verts.append(Vector3(p[1].to_float(), p[2].to_float(), p[3].to_float()))
		elif line.begins_with("vt "):
			var p := line.split(" ", false)
			uvs.append(Vector2(p[1].to_float(), p[2].to_float()))
		elif line.begins_with("g "):
			# OBJ group switch: only `g body` faces are part of the rendered body.
			var p := line.split(" ", false)
			in_body = p.size() >= 2 and p[1] == BODY_GROUP
		elif line.begins_with("f "):
			if not in_body:
				continue   # skip helper-* / joint-* faces (non-rendered geometry)
			var p := line.split(" ", false)
			var c := PackedInt32Array()
			for i in range(1, p.size()):
				c.append(corner.call(p[i]))
			if c.size() == 4:
				# quad → 2 tris, fixed diagonal c0-c2. WINDING REVERSED: the MakeHuman
				# base.obj faces are wound such that the naive (c0,c1,c2)/(c0,c2,c3) order
				# produced an inside-out body in Godot — front faces were culled and the
				# camera saw the mesh interior (the user-confirmed whole-body "backfaces").
				# Godot's default cull_mode=BACK treats CCW-from-camera as front-facing, so
				# we emit each triangle with its corners reversed (i0,i2,i1) to flip the
				# winding outward. Normal DIRECTION is handled INDEPENDENTLY in
				# _compute_normals (it swaps the cross operands to (c-a)×(b-a) so stored
				# normals point OUTWARD over this reversed winding) — culling keys off the
				# winding here, lighting off those normals; the two are not coupled.
				tris.append(c[0]); tris.append(c[2]); tris.append(c[1])
				tris.append(c[0]); tris.append(c[3]); tris.append(c[2])
				body_faces += 1
			elif c.size() == 3:
				# REVERSED winding (see the quad case above): (c0,c2,c1) instead of (c0,c1,c2).
				tris.append(c[0]); tris.append(c[2]); tris.append(c[1])
				body_faces += 1
			# (ngons >4 not present in this mesh; ignore defensively)
	f.close()
	if base_verts.is_empty() or body_faces == 0:
		push_error("body_converter: no `g %s` faces found in %s" % [BODY_GROUP, path])
		return {}
	# Leading base verts that belong to the rendered body (the body group is the
	# contiguous leading `v` block in MakeHuman's base.obj). The feet-to-origin lift
	# uses THIS range so helper-* verts (e.g. the skirt below the feet) don't drag
	# the body off the floor. Derived from the base verts actually referenced by the
	# rendered body faces (highest +1). NOTE: computed here, NOT inside the `corner`
	# lambda — a GDScript lambda captures outer locals by value, so an assignment to
	# body_base_vmax inside it would not propagate out.
	for b in render_to_base:
		body_base_vmax = maxi(body_base_vmax, b)
	return {
		"base_verts": base_verts,
		"render_pos": render_pos,
		"render_uv": render_uv,
		"render_to_base": render_to_base,
		"tris": tris,
		"base_vert_count": base_verts.size(),
		"body_vert_count": body_base_vmax + 1,
	}


## Parse a `.target`: comment lines start with '#'; data lines are
## `<vertex_index> <dx> <dy> <dz>` (MakeHuman units). Returns {index: Vector3}.
func _parse_target(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open target %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var out := {}
	while not f.eof_reached():
		var line := f.get_line().strip_edges()
		if line == "" or line.begins_with("#"):
			continue
		var p := line.split(" ", false)
		if p.size() < 4:
			continue
		var idx := p[0].to_int()
		out[idx] = Vector3(p[1].to_float(), p[2].to_float(), p[3].to_float())
	f.close()
	return out


## Smooth per-vertex normals from the triangulated mesh (area-weighted accumulate).
## Deterministic: triangles iterated in index order.
##
## NORMAL DIRECTION vs WINDING — these are INDEPENDENT in Godot: backface culling
## keys off the triangle WINDING (ARRAY_INDEX order) while lighting keys off the
## stored NORMAL vectors. The winding was reversed (i0,i2,i1) in _parse_obj so the
## mesh renders FRONT faces (cull_mode=BACK) — that is correct and must NOT change.
## But the naive face normal (verts[b]-verts[a])×(verts[c]-verts[a]) over that
## reversed winding points INWARD, which inverts lighting. So we compute the cross
## with the operands SWAPPED — (verts[c]-verts[a])×(verts[b]-verts[a]) — yielding
## OUTWARD-pointing per-vertex normals for correct lighting, while ARRAY_INDEX (the
## winding the culler uses) is untouched. (Verified: stored-normal radial dot flips
## from negative/inward to positive/outward; signed volume is unchanged.)
func _compute_normals(verts: PackedVector3Array, tris: PackedInt32Array,
		render_to_base: PackedInt32Array) -> PackedVector3Array:
	# CORRECT BY CONSTRUCTION (replaces split-then-reweld, b12bcd7). Normals are
	# accumulated onto the UN-SPLIT BASE topology, not per render vertex: a UV seam
	# splits one base vertex into N coincident render verts (distinct UVs, same `v`),
	# and a per-render-vertex accumulation would let each split see only its island's
	# faces — yielding different normals and a hard shading crease along every island
	# edge (back-of-head centre, head->neck, inner legs). Instead each triangle's
	# (area-weighted, un-normalized cross-product) face normal is added to the
	# accumulator of each corner's BASE vertex (render-corner -> base via render_to_base).
	# After all faces, normalize per base vertex ONCE, then assign each render vertex the
	# normal of ITS base vertex. The duplicates therefore inherit the same welded-topology
	# normal by construction — no reweld step, no positional assumption.
	var rn := verts.size()
	assert(render_to_base.size() == rn and rn > 0,
		"_compute_normals: render_to_base must be one entry per render vertex")
	# size the base accumulator from the max base index referenced.
	var base_count := 0
	for b in render_to_base:
		base_count = maxi(base_count, b + 1)
	var base_n := PackedVector3Array()
	base_n.resize(base_count)   # zero-initialised
	var t := 0
	while t < tris.size():
		var a := tris[t]
		var b2 := tris[t + 1]
		var c := tris[t + 2]
		# OUTWARD face normal over the reversed (i0,i2,i1) winding from _parse_obj:
		# operands SWAPPED (c-a)×(b-a) so normals point outward for correct lighting,
		# while ARRAY_INDEX (the cull winding) is untouched. (See header note above.)
		var fn := (verts[c] - verts[a]).cross(verts[b2] - verts[a])
		base_n[render_to_base[a]] += fn
		base_n[render_to_base[b2]] += fn
		base_n[render_to_base[c]] += fn
		t += 3
	# normalize per BASE vertex once.
	for i in base_count:
		var ln := base_n[i]
		base_n[i] = ln.normalized() if ln.length() > 1e-9 else Vector3.UP
	# scatter the base-vertex normal to every render vertex that came from it.
	var normals := PackedVector3Array()
	normals.resize(rn)
	for i in rn:
		normals[i] = base_n[render_to_base[i]]
	return normals


## A zero ARRAY_TANGENT delta for a blendshape: 4 floats (x,y,z,w) per render vertex,
## all zero. RELATIVE blendshapes compose final = base + Σ wᵢ·Δ; a zero delta keeps the
## base tangent. We don't morph tangents on the GPU for the same octahedral reason normals
## are zeroed (see the macro-blendshape note); the CPU re-bake handles shading.
func _zero_tangent_delta(rn: int) -> PackedFloat32Array:
	var tg := PackedFloat32Array()
	tg.resize(rn * 4)   # zero-initialised
	return tg


## Per-vertex tangents (ARRAY_TANGENT format: PackedFloat32Array, 4 floats/vertex =
## tangent.xyz + handedness w). Lengyel's method: accumulate per-triangle tangent/bitangent
## from UV gradients, then Gram-Schmidt-orthogonalize against the (already seam-welded)
## normal and store the handedness sign so a normal map decodes correctly. Deterministic
## (triangles iterated in index order). NOT seam-welded: tangents are UV-parameterised and
## split corners carry distinct UVs, so each side's own tangent is the correct one.
func _compute_tangents(verts: PackedVector3Array, uvs: PackedVector2Array,
		tris: PackedInt32Array, normals: PackedVector3Array) -> PackedFloat32Array:
	var n := verts.size()
	var tan := PackedVector3Array()   # accumulated tangent
	var bit := PackedVector3Array()   # accumulated bitangent
	tan.resize(n)
	bit.resize(n)
	for i in n:
		tan[i] = Vector3.ZERO
		bit[i] = Vector3.ZERO
	var t := 0
	while t < tris.size():
		var ia := tris[t]
		var ib := tris[t + 1]
		var ic := tris[t + 2]
		var e1 := verts[ib] - verts[ia]
		var e2 := verts[ic] - verts[ia]
		var d1 := uvs[ib] - uvs[ia]
		var d2 := uvs[ic] - uvs[ia]
		var denom := d1.x * d2.y - d2.x * d1.y
		if absf(denom) > 1e-12:
			var r := 1.0 / denom
			var sd := (e1 * d2.y - e2 * d1.y) * r   # tangent dir for this tri
			var td := (e2 * d1.x - e1 * d2.x) * r   # bitangent dir for this tri
			tan[ia] += sd; tan[ib] += sd; tan[ic] += sd
			bit[ia] += td; bit[ib] += td; bit[ic] += td
		t += 3
	var out := PackedFloat32Array()
	out.resize(n * 4)
	for i in n:
		var nrm := normals[i]
		var tv := tan[i]
		# Gram-Schmidt: project the tangent off the normal, then normalize.
		tv = (tv - nrm * nrm.dot(tv))
		if tv.length() <= 1e-9:
			# Degenerate (no usable UV gradient) — pick any vector orthogonal to nrm.
			tv = nrm.cross(Vector3.RIGHT)
			if tv.length() <= 1e-9:
				tv = nrm.cross(Vector3.UP)
		tv = tv.normalized()
		# Handedness: +1 if (n×t) agrees with the bitangent, else -1.
		var w := -1.0 if nrm.cross(tv).dot(bit[i]) < 0.0 else 1.0
		var o := i * 4
		out[o] = tv.x
		out[o + 1] = tv.y
		out[o + 2] = tv.z
		out[o + 3] = w
	return out
