## Body asset converter — MakeHuman CC0 base mesh + macro `.target` morphs → a
## Godot `ArrayMesh` resource with working blendshapes.
##
## This is the §1 pipeline of docs/decisions/body-and-locomotion-slice.md:
## direct `.target`-ASCII parsing (NOT headless Blender / MPFB). The input is
## pure text (OBJ + ASCII sparse vertex-delta `.target` files), all CC0 from the
## pinned MakeHuman source (makehumancommunity/makehuman v1.3.0). The output is a
## deterministic, byte-stable `ArrayMesh` carrying the base mesh + one blendshape
## per selected macro axis anchor.
##
## Run headless (windowed under xvfb per the project's verification posture):
##   MAKEHUMAN_SRC=/path/to/makehuman/source \
##   xvfb-run -a godot4 --path . res://tools/body_converter.tscn --quit-after 600
##
## In the nix derivation the MAKEHUMAN_SRC env var points at the pinned
## fetchFromGitHub store path; in a dev run it points at the prefetched source.
## If MAKEHUMAN_SRC is unset, falls back to a `makehuman/` dir at the repo root.
##
## Outputs (committed, regenerated by `nix build .#body-assets`):
##   res://assets/body/base_body.res        — ArrayMesh + blendshapes
##   res://assets/body/base_body.manifest.json — axis → blendshape index map + provenance
##
## Determinism: vertices in OBJ order, quads triangulated with a fixed diagonal
## (v0-v1-v2, v0-v2-v3) in stable face order, sparse deltas scattered onto a
## zero base in ascending vertex-index order. Same pinned input → identical mesh.
extends Node

## MakeHuman → meters. base.obj spans ~16.94 MH units head-to-toe; × 0.1 ≈ 1.69 m,
## a real adult height (units-and-scale.md: 1u = 1m, ~1.7–1.8 m adult).
const MH_TO_METERS := 0.1

const OUT_DIR := "res://assets/body"
const OUT_MESH := "res://assets/body/base_body.res"
const OUT_MANIFEST := "res://assets/body/base_body.manifest.json"

## The macro axis anchors imported as blendshapes for Slice 1. Each entry is a
## clean CC0 anchor `.target` (relative to <src>/makehuman/data/targets/) whose
## sparse deltas displace the base mesh along ONE macro axis. AGE is mandatory
## (it feeds the §2.2 NSFW gate); gender / muscle / weight / height accompany it.
## (MakeHuman stores age/gender as race-keyed combination targets — the base mesh
## is the caucasian, ~50%-gender, young, average-everything anchor — so the age
## and gender axes are anchored on the caucasian young/old/baby/child + male
## targets, which is the documented MakeHuman macro layout.)
const AXIS_TARGETS := [
	# axis name           # .target path under data/targets/
	["age_old",    "macrodetails/caucasian-female-old.target"],
	["age_baby",   "macrodetails/caucasian-female-baby.target"],
	["age_child",  "macrodetails/caucasian-female-child.target"],
	["gender_male", "macrodetails/caucasian-male-young.target"],
	["muscle_max", "macrodetails/universal-female-young-maxmuscle-averageweight.target"],
	["weight_max", "macrodetails/universal-female-young-averagemuscle-maxweight.target"],
	["height_max", "macrodetails/height/female-young-averagemuscle-averageweight-maxheight.target"],
]


func _ready() -> void:
	var code := _run()
	get_tree().quit(code)


func _src_root() -> String:
	var env := OS.get_environment("MAKEHUMAN_SRC")
	if env != "":
		return env.path_join("makehuman").path_join("data") if not env.ends_with("data") else env
	# fallback: vendored CC0 subset (vendor/makehuman-cc0/data/) — works on any
	# platform with only Godot, no fetch, no nix. Same v1.3.0 content as the nix
	# derivation's pinned fetchFromGitHub source → byte-identical output.
	return ProjectSettings.globalize_path("res://vendor/makehuman-cc0/data")


func _run() -> int:
	var data_root := _src_root()
	print("body_converter: data root = %s" % data_root)

	var obj_path := data_root.path_join("3dobjs/base.obj")
	var parsed := _parse_obj(obj_path)
	if parsed.is_empty():
		push_error("body_converter: failed to parse %s" % obj_path)
		return 1

	var base_verts: PackedVector3Array = parsed["verts"]      # MH-space, raw
	var tris: PackedInt32Array = parsed["tris"]                # triangulated indices
	var n := base_verts.size()
	print("body_converter: %d vertices, %d triangle indices (%d tris)" % [n, tris.size(), tris.size() / 3])

	# --- scale + feet-to-origin transform (1u = 1m) ---------------------------
	var min_y := INF
	for v in base_verts:
		min_y = min(min_y, v.y)
	# scaled positions, lifted so the lowest vertex (feet) sits at y = 0
	var scaled_base := PackedVector3Array()
	scaled_base.resize(n)
	for i in n:
		var v := base_verts[i]
		scaled_base[i] = Vector3(v.x * MH_TO_METERS, (v.y - min_y) * MH_TO_METERS, v.z * MH_TO_METERS)

	# --- normals from the triangulated base (smooth, deterministic) -----------
	var normals := _compute_normals(scaled_base, tris)

	# --- build the surface arrays ---------------------------------------------
	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = scaled_base
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_INDEX] = tris

	# --- blendshapes: one per selected macro anchor ---------------------------
	var mesh := ArrayMesh.new()
	mesh.blend_shape_mode = Mesh.BLEND_SHAPE_MODE_NORMALIZED if false else Mesh.BLEND_SHAPE_MODE_RELATIVE
	var manifest_axes := []
	var blend_arrays := []   # one ARRAY for each blendshape, in registration order

	for entry in AXIS_TARGETS:
		var axis_name: String = entry[0]
		var rel: String = entry[1]
		var tpath := data_root.path_join("targets").path_join(rel)
		var deltas := _parse_target(tpath)
		if deltas.is_empty():
			push_error("body_converter: target had no deltas or failed to load: %s" % tpath)
			return 1
		# scatter sparse deltas onto a copy of the base, scaled (deltas are in MH
		# units, same as vertices). A blendshape surface array is the FULL morphed
		# vertex set (Godot stores absolute positions per blendshape in RELATIVE
		# mode it subtracts the base internally).
		var morphed := scaled_base.duplicate()
		var moved := 0
		for idx in deltas:
			var d: Vector3 = deltas[idx]
			if idx < 0 or idx >= n:
				continue
			morphed[idx] = morphed[idx] + Vector3(d.x * MH_TO_METERS, d.y * MH_TO_METERS, d.z * MH_TO_METERS)
			moved += 1
		var ba := []
		ba.resize(Mesh.ARRAY_MAX)
		ba[Mesh.ARRAY_VERTEX] = morphed
		ba[Mesh.ARRAY_NORMAL] = normals  # keep base normals; Slice 1 morph proof is positional
		mesh.add_blend_shape(axis_name)
		blend_arrays.append(ba)
		manifest_axes.append({
			"axis": axis_name,
			"blend_shape_index": manifest_axes.size(),
			"source_target": "targets/" + rel,
			"moved_vertices": moved,
		})
		print("body_converter: blendshape '%s' <- %s (%d verts moved)" % [axis_name, rel, moved])

	# add the surface with all blendshapes attached
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays, blend_arrays)
	mesh.surface_set_name(0, "body")

	# --- write outputs --------------------------------------------------------
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var err := ResourceSaver.save(mesh, OUT_MESH, ResourceSaver.FLAG_COMPRESS)
	if err != OK:
		push_error("body_converter: failed to save mesh (err %d)" % err)
		return 1
	print("body_converter: wrote %s" % OUT_MESH)

	var manifest := {
		"_comment": "Generated by tools/body_converter.gd from MakeHuman CC0 source. DO NOT hand-edit; regenerate with `nix build .#body-assets`.",
		"license": "CC0-1.0 (MakeHuman core base mesh + targets, explicitly CC0 since Sept 2020)",
		"source": {
			"owner": "makehumancommunity",
			"repo": "makehuman",
			"rev": "v1.3.0",
			"sha256": "sha256-x0v/SkwtOl1lkVi2TRuIgx2Xgz4JcWD3He7NhU44Js4=",
		},
		"mh_to_meters": MH_TO_METERS,
		"vertex_count": n,
		"triangle_count": tris.size() / 3,
		"axes": manifest_axes,
	}
	var mf := FileAccess.open(OUT_MANIFEST, FileAccess.WRITE)
	if mf == null:
		push_error("body_converter: cannot write manifest")
		return 1
	mf.store_string(JSON.stringify(manifest, "\t"))
	mf.flush()
	mf.close()
	print("body_converter: wrote %s" % OUT_MANIFEST)
	print("body_converter: DONE")
	return 0


# ---------------------------------------------------------------------------
# Parsers — pure text → arrays. Deterministic: preserve source order.
# ---------------------------------------------------------------------------

## Parse a MakeHuman base.obj: collect `v x y z` in file order and `f` quad faces,
## triangulating each quad (a b c d) → (a b c) + (a c d) with a fixed diagonal.
## OBJ face indices are 1-based; we return 0-based triangle indices.
func _parse_obj(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open OBJ %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var verts := PackedVector3Array()
	var tris := PackedInt32Array()
	while not f.eof_reached():
		var line := f.get_line()
		if line.begins_with("v "):
			var p := line.split(" ", false)
			# p[0] == "v"
			verts.append(Vector3(p[1].to_float(), p[2].to_float(), p[3].to_float()))
		elif line.begins_with("f "):
			var p := line.split(" ", false)
			# face verts are p[1..]; each token "vidx/uvidx" — take the vertex index
			var fi := PackedInt32Array()
			for i in range(1, p.size()):
				var tok := p[i]
				var slash := tok.find("/")
				var vstr := tok.substr(0, slash) if slash != -1 else tok
				fi.append(vstr.to_int() - 1)  # 1-based → 0-based
			if fi.size() == 4:
				# quad → 2 tris, fixed diagonal v0-v2
				tris.append(fi[0]); tris.append(fi[1]); tris.append(fi[2])
				tris.append(fi[0]); tris.append(fi[2]); tris.append(fi[3])
			elif fi.size() == 3:
				tris.append(fi[0]); tris.append(fi[1]); tris.append(fi[2])
			# (ngons >4 not present in this mesh; ignore defensively)
	f.close()
	if verts.is_empty():
		return {}
	return {"verts": verts, "tris": tris}


## Parse a `.target`: comment lines start with '#'; data lines are
## `<vertex_index> <dx> <dy> <dz>` (MakeHuman units). Returns {index: Vector3}.
func _parse_target(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("body_converter: cannot open target %s (err %d)" % [path, FileAccess.get_open_error()])
		return {}
	var out := {}
	while not f.eof_reached():
		var line := f.get_line().strip_edges()
		if line == "" or line.begins_with("#"):
			continue
		var p := line.split(" ", false)
		if p.size() < 4:
			continue
		var idx := p[0].to_int()
		out[idx] = Vector3(p[1].to_float(), p[2].to_float(), p[3].to_float())
	f.close()
	return out


## Smooth per-vertex normals from the triangulated mesh (area-weighted accumulate).
## Deterministic: triangles iterated in index order.
func _compute_normals(verts: PackedVector3Array, tris: PackedInt32Array) -> PackedVector3Array:
	var n := verts.size()
	var normals := PackedVector3Array()
	normals.resize(n)
	for i in n:
		normals[i] = Vector3.ZERO
	var t := 0
	while t < tris.size():
		var a := tris[t]
		var b := tris[t + 1]
		var c := tris[t + 2]
		var fn := (verts[b] - verts[a]).cross(verts[c] - verts[a])
		normals[a] += fn
		normals[b] += fn
		normals[c] += fn
		t += 3
	for i in n:
		var ln := normals[i]
		normals[i] = ln.normalized() if ln.length() > 1e-9 else Vector3.UP
	return normals
